R
install.packages("MBESS")
require(MBESS)
c1 <- as.matrix(read.table("dat/cov_biom.dat",header=F,as.is=T))
d1 <- sqrt(diag(c1))
d2 <- as.vector(d1/1000)
c2 <- cov2cor(c1)
c3 <- sweep(sweep(c2, 1L, d2, "*"), 2L, d2, "*")
all.equal(c3,c1)
write.table(c3,file="dat/rescaled_cov_2017.dat")