---
title: "Survey evaluation"
date: "5/5/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, echo = FALSE, warning = FALSE, message = FALSE, cache=FALSE,results="asis")
```


## Summary
The SSC selected model from December 2019 was 16.2. The following are 
draft results of simply updating anticipated 2020 catches over three cases:     
1.  No AVO or other survey data     
2.  A 2020 AVO data point that is equal to the lowest on record (from Sail drones)     
3.  A 2020 AVO data point that is equal to the highest on record (from Sail drones)     

```{r fig1,results="asis",echo=FALSE}
setwd("~/_mymods/ebswp/doc")
source("../pm_20.R")
plot_avo(modlst[c(1,4,5)])
```

```{r fig2,results="asis",echo=FALSE}
plot_ssb(modlst[c(1,4,5)],xlim=c(2008.5,2020.5),breaks=seq(2008,2020,by=2),alpha=.2) 
```

```{r fig3,results="asis",echo=FALSE}
plot_recruitment(modlst[c(1,4,5)],xlim=c(2008.5,2020.5)) 
```

```{r dectable,results="asis",echo=FALSE}
df <- NULL

mod_scen <-c(1,4,5) 
for (ii in mod_scen) {
    x       <- modlst[[ii]]
    ssb    <- x$nextyrssbs;         names(ssb)            <- paste0("${B}_{", nextyr ,"}$")
    ssbcv  <- round(x$nextyrssb.cv,2);  names(ssbcv)      <- paste0("$CV_{B_{", nextyr ,"}}$")
    Bmsy   <- x$bmsys;         names(Bmsy)                <- "$B_{MSY}$"
    Bmsycv <- round(x$bmsy.cv,2); names(Bmsycv)           <- "$CV_{B_{MSY}}$"
    spr    <- paste0(round(x$sprmsy*100,0),"\\%");names(spr) <- "SPR rate at $F_{MSY}$"
    b35    <- x$b35s ;                 names(b35)         <- paste0("$B_{35\\%}$")
    pbmsy  <- paste0(round(100*x$ssb1/x$bmsy,0),"\\%");    names(pbmsy)<- paste0("${B}_{", nextyr ,"}/B_{MSY}$")
    bzero  <- x$b0s ;                 names(bzero)        <- paste0("$B_0$")
    dynb0  <- x$dynb0s;      names(dynb0)                 <- "Est. $B_{2020} / B_{2020,no fishing}$"
    b_bmsy <- paste0(round(x$curssb/x$bmsy*100,0),"\\%");      names(b_bmsy) <- "$B_{2020} / B_{MSY}$"
    steep  <- round(x$steep,2);               names(steep) <- "Steepness"
    v      <- c(ssb, ssbcv, Bmsy, Bmsycv, pbmsy, bzero,b35, spr ,steep, dynb0,b_bmsy)
    df     <- cbind(df, v)
 }
df <- data.frame(rownames(df), df, row.names = NULL)
names(df) <- c("Component",mod_names[mod_scen])
tab <- xtable(df, caption = "Summary of model 16.2 results and the stock condition for EBS pollock. Biomass units are thousands of t.", label = "tab:res_summ", digits = 3)
print(tab, caption.placement = "top", include.rownames = FALSE, sanitize.text.function = function(x){x})


df <- NULL
mod_scen <- c(1,4,5)
for (ii in mod_scen) {
    x       <- modlst[[ii]]
    abcbiom <- paste0(x$ABC_biom1s,",000");         
    names(abcbiom)    <- paste0(nextyr," fishable biomass (GM)")
    msybiom           <- paste0(x$bmsyrs,",000");         
    names(msybiom)    <- paste0("Equilibrium fishable biomass at MSY")
    msyr        <- round(x$harmeanF,3);  
    names(msyr) <- ("MSY R (HM)")
    tier1abc        <- x$maxabc1s;  
    names(tier1abc) <- paste(nextyr,"Tier 1 ABC")
    fofl            <- x$arithmeanF;         
    names(fofl)     <- paste(nextyr,"Tier 1 $F_{OFL}$")
    ofl        <- x$ofl1s;         
    names(ofl) <- paste(nextyr,"Tier 1 OFL")
    fabc        <- round(0.85*x$harmeanF,3);  
    names(fabc) <- ("MSY R (HM)")
    recabc         <- x$abc1s;  
    names(recabc)  <- "Recommended ABC"
    v      <- c(abcbiom,msybiom,msyr,tier1abc,fofl,ofl,fabc,recabc)
    df     <- cbind(df, v)
}
df <- data.frame(rownames(df), df, row.names = NULL)
names(df) <- c("Component",mod_names[mod_scen])
tabcap<- "Summary results of Tier 1 2020 yield projections for EBS pollock."
tab <- xtable(df, caption = tabcap, label = paste0("tab:tab2"), digits = 3,align=paste0("ll",strrep("r",length(mod_scen))) )
print(tab, caption.placement = "top", include.rownames = FALSE, sanitize.text.function = function(x){x})
```

# The end
Bye
