---
title: "Chapter 1: Assessment of the Walleye Pollock Stock \\ in the Eastern Bering Sea"
date: "`r format(Sys.time(), '%H:%M %B %d, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document:
    toc: true
    highlight: zenburn
    fig_caption: yes
    includes:
      in_header: mystyles.sty
    keep_tex: yes
    template: ms.tex
fontsize: 11pt
header-includes:
  - \usepackage{fontspec}
geometry: margin=1in
fontfamily: mathpazo
#bibliography: ~/OneDrive/myref.bib
---
\pagenumbering{gobble}

```{r global_options, include=FALSE}

library(knitr)
opts_chunk$set(fig.width = 6, fig.height = 8, echo = FALSE, warning = FALSE, message = FALSE, cache=FALSE,results="asis")
clean_cache(clean = TRUE)
#include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
#echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
#message = FALSE prevents messages that are generated by code from appearing in the finished file.
#warning = FALSE prevents warnings that are generated by code from appearing in the finished.
#fig.cap = "..." adds a caption to graphical results.
#To set global options that apply to every chunk in your file, call knitr::opts_chunk$set in a code chunk. Knitr will treat each option that you pass to 
```
----


\begin{centering}
  James Ianelli, Stan Kotwicki, Taina Honkalehto, \\
  Abigail McCarthy, Sarah Stienessen, Kirstin Holsman,\\
  Elizabeth Siddon and Ben Fissel \\
\fontfamily{cmr}
\fontsize{10}{12}
\selectfont
  Alaska Fisheries Science Center, National Marine Fisheries Service \\
  National Oceanic and Atmospheric Administration \\ 
  7600 Sand Point Way NE., Seattle, WA 98115-6349 \\
`r format(Sys.time(), '%B %d, %Y')` \\
\end{centering}
----

```{r giddy}
# settings for speed/updating 
doplots <- F
domcmc  <- F
doproj  <- F
source("../pm_19.R")
```

\clearpage
```{r modfits, results = "asis"}
# Fit to data------------------- 
# Comparison among variance constraints for RW in survey selectivity/q
.MODELFN  = c("r_1","r_2","r_3","r_4","r_5")
prof_names  = c("CV70%","CV50%","CV20%","CV10%","CV05%")
fn       <- paste0("../runs/redqvar/prof/",.MODELFN)
proflst   <- lapply(fn, read_admb)
names(proflst) <- prof_names
nmods <- length(prof_names)
for (i in 1:nmods) {
  proflst[[i]] <- c(proflst[[i]],get_vars(proflst[[i]]))
}
df <- tab_fit(proflst)
tab <- xtable(df, caption = "Goodness of fit to primary data used for assessment model parameter estimation profiling over different constraints on the extent bottom-trawl survey selectivity/availability is allowed to change;  EBS pollock.", label = "tab:mod_prof_fits")#, digits = 3,align="llrrrrr")
print(tab, caption.placement = "top", include.rownames = FALSE, sanitize.text.function = function(x){x})

# Fit to data------------------- 
if (is.null(mod_scen)) mod_scen <- c(2,3)
df <- tab_fit(modlst,mod_scen)
tab <- xtable(df, caption = "Goodness of fit to primary data used for assessment model parameter estimation for different model configurations, EBS pollock.", label = "tab:mod_fits", digits = 3,align="llrrrrr")
print(tab, caption.placement = "top", include.rownames = FALSE, sanitize.text.function = function(x){x})

```
<!--
#```{r child = 'text.Rmd'}
#```
#```{r child = 'ref.Rmd'}
#```
```{r child = 'tab.Rmd'}
```
```{r child = 'figs.Rmd'}
```
#```{r child = 'model.Rmd'}
#```
#```{r child = 'App.Rmd'}
```
-->
 #\tableofcontents

 #\listoftables

 #\listoffigures


-->