---
title: "Chapter 1: Assessment of the Walleye Pollock Stock \\ in the Eastern Bering Sea"
date: "`r format(Sys.time(), '%H:%M %B %d, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document:
    toc: true
    highlight: zenburn
    fig_caption: yes
    includes:
      in_header: mystyles.sty
    keep_tex: yes
    template: ms.tex
fontsize: 11pt
header-includes:
  - \usepackage{fontspec}
geometry: margin=1in
fontfamily: mathpazo
bibliography: ~/OneDrive/myref.bib
---
\pagenumbering{gobble}

```{r global_options, include=FALSE}

library(knitr)
opts_chunk$set(fig.width = 6, fig.height = 8, echo = FALSE, warning = FALSE, message = FALSE, cache=FALSE,results="asis")
clean_cache(clean = TRUE)
#include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
#echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
#message = FALSE prevents messages that are generated by code from appearing in the finished file.
#warning = FALSE prevents warnings that are generated by code from appearing in the finished.
#fig.cap = "..." adds a caption to graphical results.
#To set global options that apply to every chunk in your file, call knitr::opts_chunk$set in a code chunk. Knitr will treat each option that you pass to 
```
----


\begin{centering}
  James Ianelli, Stan Kotwicki, Taina Honkalehto, \\
  Abigail McCarthy, Sarah Stienessen, Kirstin Holsman,\\
  Elizabeth Siddon and Ben Fissel \\
\fontfamily{cmr}
\fontsize{10}{12}
\selectfont
  Alaska Fisheries Science Center, National Marine Fisheries Service \\
  National Oceanic and Atmospheric Administration \\ 
  7600 Sand Point Way NE., Seattle, WA 98115-6349 \\
`r format(Sys.time(), '%B %d, %Y')` \\
\end{centering}
----

```{r giddy}
# settings for speed/updating 
doplots <- F
domcmc  <- F
doproj  <- F
source("../runs/pm_19.R")
```

#```{r child = 'text.Rmd'}
#```
```{r child = 'ref.Rmd'}
```
\newpage
#```{r child = 'tab.Rmd'}
#```
\newpage
#```{r child = 'figs.Rmd'}
#```
\newpage
```{r child = 'model.Rmd'}
```
\newpage
#```{r child = 'App.Rmd'}
# \newpage
# \tableofcontents

# \listoftables

# \listoffigures
```

