---
format: 
  pdf:
output:
  pdf_document: default
  html_document: default
  output: 
  bookdown::pdf_document2:
    highlight: zenburn
    latex_engine: xelatex
    fig_caption: yes
    number_sections: false
    toc: false
    includes:
      in_header: "paramble.tex"
    keep_tex: yes
fontsize: 11pt
header-includes:
  
geometry: margin=1in
---
# Parameter estimates for the EBS pollock reference model 
Includes parameter set from Model 20, uses the VAST index and age-composition
results  (from bottom trawl survey) and includes the Northern Bering Sea segment.
\fontsize{7}{9}

\begin{table}[ht]
\centering
\begin{tabular}{lrrrrrrr}
\hline
Parameter & Rhat & n\_eff & mean & sd & 2.5\% & 50\% & 97.5\% \\ 
\hline
log\_avgrec & 1.0 & 589 & 9.8 & 0.1 & 9.6 & 9.8 & 10.0 \\ 
  log\_avginit & 1.0 & 3858 & 3.9 & 0.7 & 2.4 & 3.9 & 5.3 \\ 
  log\_avg\_F & 1.0 & 2219 & -1.0 & 0.1 & -1.2 & -1.0 & -0.9 \\ 
  log\_q\_ats & 1.0 & 2267 & -0.6 & 0.1 & -0.7 & -0.6 & -0.4 \\ 
  log\_Rzero & 1.0 & 12000 & 10.2 & 0.2 & 9.9 & 10.2 & 10.6 \\ 
  steepness & 1.0 & 12000 & 0.6 & 0.1 & 0.5 & 0.6 & 0.7 \\ 
  log\_q\_cpue & 1.0 & 1806 & 0.8 & 0.2 & 0.5 & 0.8 & 1.2 \\ 
  log\_q\_avo & 1.0 & 12000 & -8.2 & 0.1 & -8.4 & -8.2 & -8.1 \\ 
  log\_initdevs[1] & 1.0 & 4458 & 4.3 & 0.8 & 2.7 & 4.3 & 5.9 \\ 
  log\_initdevs[2] & 1.0 & 4355 & 3.8 & 0.8 & 2.2 & 3.8 & 5.4 \\ 
  log\_initdevs[3] & 1.0 & 5360 & 2.1 & 0.9 & 0.3 & 2.1 & 3.9 \\ 
  log\_initdevs[4] & 1.0 & 6918 & 0.9 & 1.2 & -1.7 & 1.0 & 3.0 \\ 
  log\_initdevs[5] & 1.0 & 5591 & 1.7 & 1.0 & -0.2 & 1.7 & 3.6 \\ 
  log\_initdevs[6] & 1.0 & 7723 & 0.6 & 1.2 & -2.0 & 0.7 & 2.8 \\ 
  log\_initdevs[7] & 1.0 & 12000 & -1.1 & 1.6 & -4.6 & -0.9 & 1.7 \\ 
  log\_initdevs[8] & 1.0 & 12000 & -1.6 & 1.7 & -5.3 & -1.5 & 1.3 \\ 
  log\_initdevs[9] & 1.0 & 12000 & -1.7 & 1.7 & -5.3 & -1.6 & 1.2 \\ 
  log\_initdevs[10] & 1.0 & 12000 & -1.7 & 1.6 & -5.2 & -1.6 & 1.1 \\ 
  sel\_devs\_ats[181] & 1.0 & 372 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[182] & 1.0 & 337 & 0.6 & 0.3 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[183] & 1.0 & 380 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[184] & 1.0 & 382 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[185] & 1.0 & 373 & 0.7 & 0.4 & -0.1 & 0.7 & 1.4 \\ 
  sel\_devs\_ats[186] & 1.0 & 375 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[187] & 1.0 & 383 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[188] & 1.0 & 382 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[189] & 1.0 & 346 & 0.6 & 0.3 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[190] & 1.0 & 388 & 0.6 & 0.4 & -0.2 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[191] & 1.0 & 401 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[192] & 1.0 & 393 & 0.7 & 0.4 & -0.0 & 0.7 & 1.4 \\ 
  sel\_devs\_ats[193] & 1.0 & 393 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[194] & 1.0 & 403 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[195] & 1.0 & 394 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[196] & 1.0 & 364 & 0.6 & 0.4 & -0.1 & 0.6 & 1.3 \\ 
  sel\_devs\_ats[197] & 1.0 & 423 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[198] & 1.0 & 424 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[199] & 1.0 & 432 & 0.6 & 0.4 & -0.2 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[200] & 1.0 & 426 & 0.6 & 0.4 & -0.2 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[201] & 1.0 & 433 & 0.6 & 0.4 & -0.2 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[202] & 1.0 & 429 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_devs\_ats[203] & 1.0 & 393 & 0.6 & 0.4 & -0.1 & 0.6 & 1.4 \\ 
  sel\_coffs\_fsh[1] & 1.0 & 12000 & -4.9 & 0.8 & -6.5 & -4.9 & -3.5 \\ 
  sel\_coffs\_fsh[2] & 1.0 & 12000 & -2.9 & 0.6 & -4.0 & -2.9 & -1.8 \\ 
  sel\_coffs\_fsh[3] & 1.0 & 6822 & -1.6 & 0.5 & -2.5 & -1.6 & -0.6 \\ 
  sel\_coffs\_fsh[4] & 1.0 & 5945 & -0.4 & 0.4 & -1.2 & -0.4 & 0.3 \\ 
  sel\_coffs\_fsh[5] & 1.0 & 5175 & -0.2 & 0.4 & -1.0 & -0.2 & 0.5 \\ 
  sel\_coffs\_fsh[6] & 1.0 & 5377 & -0.1 & 0.4 & -0.8 & -0.1 & 0.6 \\ 
  sel\_coffs\_fsh[7] & 1.0 & 5537 & -0.0 & 0.3 & -0.7 & -0.0 & 0.6 \\ 
  sel\_coffs\_fsh[8] & 1.0 & 5708 & 0.1 & 0.3 & -0.6 & 0.1 & 0.7 \\ 
  sel\_coffs\_fsh[9] & 1.0 & 6099 & 0.2 & 0.3 & -0.5 & 0.2 & 0.8 \\ 
  sel\_coffs\_fsh[10] & 1.0 & 6832 & 0.4 & 0.3 & -0.3 & 0.4 & 1.0 \\ 
  sel\_coffs\_fsh[11] & 1.0 & 7425 & 0.6 & 0.3 & -0.1 & 0.6 & 1.3 \\ 
  sel\_coffs\_fsh[12] & 1.0 & 8322 & 0.9 & 0.3 & 0.2 & 0.9 & 1.5 \\ 
  sel\_coffs\_ats[1] & 1.0 & 3527 & -0.2 & 0.2 & -0.6 & -0.2 & 0.3 \\ 
  sel\_coffs\_ats[2] & 1.0 & 2564 & -0.2 & 0.3 & -0.7 & -0.2 & 0.3 \\ 
  sel\_coffs\_ats[3] & 1.0 & 2458 & -0.0 & 0.3 & -0.5 & 0.0 & 0.5 \\ 
  sel\_coffs\_ats[4] & 1.0 & 1826 & 0.1 & 0.2 & -0.4 & 0.1 & 0.6 \\ 
  sel\_coffs\_ats[5] & 1.0 & 2617 & 0.2 & 0.3 & -0.4 & 0.2 & 0.7 \\ 
  sel\_coffs\_ats[6] & 1.0 & 2046 & 0.3 & 0.3 & -0.3 & 0.3 & 0.8 \\ 
  sel\_coffs\_ats[7] & 1.0 & 812 & 0.4 & 0.2 & -0.0 & 0.4 & 0.9 \\ 
  sel\_slp\_bts & 1.0 & 4280 & 1.0 & 0.0 & 0.9 & 1.0 & 1.1 \\ 
  sel\_a50\_bts & 1.0 & 3326 & 6.2 & 0.1 & 5.9 & 6.2 & 6.5 \\ 
  sel\_age\_one\_bts & 1.0 & 5788 & -3.2 & 0.1 & -3.4 & -3.2 & -3.0 \\ 
  sel\_slp\_bts\_dev[1] & 1.0 & 9501 & -0.8 & 0.2 & -1.3 & -0.8 & -0.4 \\ 
  sel\_slp\_bts\_dev[2] & 1.0 & 7515 & -0.2 & 0.3 & -0.8 & -0.2 & 0.3 \\ 
  sel\_slp\_bts\_dev[3] & 1.0 & 7516 & 0.0 & 0.1 & -0.2 & 0.0 & 0.3 \\ 
  sel\_slp\_bts\_dev[4] & 1.0 & 8797 & -0.5 & 0.2 & -0.9 & -0.5 & -0.1 \\ 
  sel\_slp\_bts\_dev[5] & 1.0 & 7405 & -0.4 & 0.2 & -0.7 & -0.4 & -0.1 \\ 
  sel\_slp\_bts\_dev[6] & 1.0 & 7027 & -0.4 & 0.2 & -0.9 & -0.4 & -0.0 \\ 
  sel\_slp\_bts\_dev[7] & 1.0 & 7905 & -0.5 & 0.3 & -1.1 & -0.5 & 0.1 \\ 
  sel\_slp\_bts\_dev[8] & 1.0 & 5244 & -0.3 & 0.3 & -1.0 & -0.3 & 0.3 \\ 
  sel\_slp\_bts\_dev[9] & 1.0 & 12000 & 0.4 & 0.2 & 0.0 & 0.4 & 0.9 \\ 
  sel\_slp\_bts\_dev[10] & 1.0 & 12000 & 0.3 & 0.2 & -0.1 & 0.3 & 0.7 \\ 
  sel\_slp\_bts\_dev[11] & 1.0 & 9329 & 0.2 & 0.2 & -0.2 & 0.2 & 0.7 \\ 
  sel\_slp\_bts\_dev[12] & 1.0 & 12000 & 0.4 & 0.2 & -0.1 & 0.4 & 0.8 \\ 
  sel\_slp\_bts\_dev[13] & 1.0 & 12000 & 0.3 & 0.2 & -0.0 & 0.3 & 0.6 \\ 
  sel\_slp\_bts\_dev[14] & 1.0 & 12000 & 0.2 & 0.2 & -0.1 & 0.2 & 0.5 \\ 
  sel\_slp\_bts\_dev[15] & 1.0 & 12000 & -0.2 & 0.1 & -0.4 & -0.2 & 0.1 \\ 
  sel\_slp\_bts\_dev[16] & 1.0 & 9737 & -0.3 & 0.1 & -0.6 & -0.3 & 0.0 \\ 
  sel\_slp\_bts\_dev[17] & 1.0 & 12000 & -0.5 & 0.1 & -0.7 & -0.5 & -0.3 \\ 
  sel\_slp\_bts\_dev[18] & 1.0 & 12000 & -0.5 & 0.1 & -0.8 & -0.5 & -0.3 \\ 
  sel\_slp\_bts\_dev[19] & 1.0 & 10787 & -0.2 & 0.2 & -0.5 & -0.2 & 0.0 \\ 
  sel\_slp\_bts\_dev[20] & 1.0 & 12000 & -0.5 & 0.1 & -0.7 & -0.4 & -0.2 \\ 
  sel\_slp\_bts\_dev[21] & 1.0 & 9806 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_slp\_bts\_dev[22] & 1.0 & 9148 & 0.1 & 0.1 & -0.2 & 0.1 & 0.4 \\ 
  sel\_slp\_bts\_dev[23] & 1.0 & 12000 & 0.0 & 0.1 & -0.2 & 0.0 & 0.3 \\ 
  sel\_slp\_bts\_dev[24] & 1.0 & 12000 & 0.2 & 0.1 & -0.1 & 0.2 & 0.4 \\ 
  sel\_slp\_bts\_dev[25] & 1.0 & 12000 & -0.1 & 0.1 & -0.4 & -0.1 & 0.1 \\ 
  sel\_slp\_bts\_dev[26] & 1.0 & 12000 & 0.3 & 0.2 & -0.0 & 0.3 & 0.6 \\ 
  sel\_slp\_bts\_dev[27] & 1.0 & 12000 & 0.5 & 0.1 & 0.2 & 0.5 & 0.7 \\ 
  sel\_slp\_bts\_dev[28] & 1.0 & 10104 & 0.2 & 0.1 & -0.0 & 0.2 & 0.5 \\ 
  sel\_slp\_bts\_dev[29] & 1.0 & 12000 & 0.7 & 0.2 & 0.4 & 0.7 & 1.0 \\ 
  sel\_slp\_bts\_dev[30] & 1.0 & 12000 & 0.5 & 0.1 & 0.3 & 0.5 & 0.7 \\ 
  sel\_slp\_bts\_dev[31] & 1.0 & 12000 & 0.2 & 0.1 & -0.1 & 0.2 & 0.4 \\ 
  sel\_slp\_bts\_dev[32] & 1.0 & 12000 & 0.3 & 0.1 & 0.1 & 0.3 & 0.5 \\ 
  sel\_slp\_bts\_dev[33] & 1.0 & 12000 & 0.5 & 0.1 & 0.3 & 0.5 & 0.7 \\ 
  sel\_slp\_bts\_dev[34] & 1.0 & 12000 & 0.4 & 0.1 & 0.2 & 0.4 & 0.6 \\ 
  sel\_slp\_bts\_dev[35] & 1.0 & 12000 & 0.4 & 0.1 & 0.2 & 0.4 & 0.7 \\ 
  sel\_slp\_bts\_dev[36] & 1.0 & 12000 & 0.2 & 0.1 & 0.0 & 0.2 & 0.4 \\ 
  sel\_slp\_bts\_dev[37] & 1.0 & 8758 & -0.3 & 0.1 & -0.6 & -0.3 & -0.1 \\ 
  sel\_slp\_bts\_dev[38] & 1.0 & 12000 & -0.0 & 0.1 & -0.3 & -0.0 & 0.2 \\ 
  sel\_slp\_bts\_dev[39] & 1.0 & 12000 & -0.2 & 0.2 & -0.7 & -0.2 & 0.3 \\ 
  sel\_slp\_bts\_dev[40] & 1.0 & 6637 & -0.2 & 0.1 & -0.4 & -0.2 & 0.0 \\ 
  sel\_slp\_bts\_dev[41] & 1.0 & 5860 & 0.0 & 0.1 & -0.3 & 0.0 & 0.3 \\ 
  sel\_slp\_bts\_dev[42] & 1.0 & 5135 & -0.2 & 0.1 & -0.5 & -0.2 & 0.0 \\ 
  sel\_a50\_bts\_dev[1] & 1.0 & 8251 & 0.0 & 0.1 & -0.1 & 0.0 & 0.2 \\ 
  sel\_a50\_bts\_dev[2] & 1.0 & 6046 & -0.1 & 0.1 & -0.2 & -0.1 & 0.0 \\ 
  sel\_a50\_bts\_dev[3] & 1.0 & 6455 & -0.0 & 0.0 & -0.1 & -0.0 & 0.1 \\ 
  sel\_a50\_bts\_dev[4] & 1.0 & 5898 & 0.1 & 0.1 & 0.0 & 0.1 & 0.3 \\ 
  sel\_a50\_bts\_dev[5] & 1.0 & 6286 & 0.1 & 0.1 & 0.0 & 0.1 & 0.3 \\ 
  sel\_a50\_bts\_dev[6] & 1.0 & 6336 & 0.0 & 0.1 & -0.1 & 0.0 & 0.2 \\ 
  sel\_a50\_bts\_dev[7] & 1.0 & 7412 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_a50\_bts\_dev[8] & 1.0 & 4100 & -0.2 & 0.1 & -0.4 & -0.2 & -0.0 \\ 
  sel\_a50\_bts\_dev[9] & 1.0 & 9921 & -0.2 & 0.1 & -0.4 & -0.2 & -0.1 \\ 
  sel\_a50\_bts\_dev[10] & 1.0 & 8959 & -0.2 & 0.1 & -0.3 & -0.2 & -0.0 \\ 
  sel\_a50\_bts\_dev[11] & 1.0 & 8985 & -0.2 & 0.1 & -0.3 & -0.2 & -0.0 \\ 
  sel\_a50\_bts\_dev[12] & 1.0 & 12000 & -0.2 & 0.1 & -0.3 & -0.2 & -0.1 \\ 
  sel\_a50\_bts\_dev[13] & 1.0 & 12000 & -0.1 & 0.0 & -0.2 & -0.1 & -0.0 \\ 
  sel\_a50\_bts\_dev[14] & 1.0 & 12000 & 0.0 & 0.1 & -0.1 & 0.0 & 0.1 \\ 
  sel\_a50\_bts\_dev[15] & 1.0 & 8995 & 0.2 & 0.0 & 0.1 & 0.2 & 0.3 \\ 
  sel\_a50\_bts\_dev[16] & 1.0 & 8923 & 0.2 & 0.1 & 0.1 & 0.2 & 0.3 \\ 
  sel\_a50\_bts\_dev[17] & 1.0 & 8257 & 0.3 & 0.0 & 0.2 & 0.3 & 0.4 \\ 
  sel\_a50\_bts\_dev[18] & 1.0 & 12000 & 0.2 & 0.1 & 0.1 & 0.2 & 0.3 \\ 
  sel\_a50\_bts\_dev[19] & 1.0 & 10265 & 0.1 & 0.1 & -0.0 & 0.1 & 0.2 \\ 
  sel\_a50\_bts\_dev[20] & 1.0 & 12000 & 0.2 & 0.0 & 0.1 & 0.2 & 0.3 \\ 
  sel\_a50\_bts\_dev[21] & 1.0 & 9417 & 0.1 & 0.0 & -0.0 & 0.1 & 0.2 \\ 
  sel\_a50\_bts\_dev[22] & 1.0 & 9638 & 0.0 & 0.1 & -0.1 & 0.0 & 0.2 \\ 
  sel\_a50\_bts\_dev[23] & 1.0 & 9762 & 0.1 & 0.0 & -0.0 & 0.1 & 0.2 \\ 
  sel\_a50\_bts\_dev[24] & 1.0 & 10856 & -0.0 & 0.0 & -0.1 & -0.0 & 0.1 \\ 
  sel\_a50\_bts\_dev[25] & 1.0 & 12000 & 0.1 & 0.0 & 0.0 & 0.1 & 0.2 \\ 
  sel\_a50\_bts\_dev[26] & 1.0 & 12000 & -0.0 & 0.0 & -0.1 & -0.0 & 0.0 \\ 
  sel\_a50\_bts\_dev[27] & 1.0 & 9312 & -0.1 & 0.0 & -0.2 & -0.1 & -0.0 \\ 
  sel\_a50\_bts\_dev[28] & 1.0 & 9564 & -0.0 & 0.0 & -0.1 & -0.0 & 0.1 \\ 
  sel\_a50\_bts\_dev[29] & 1.0 & 9896 & -0.2 & 0.0 & -0.3 & -0.2 & -0.1 \\ 
  sel\_a50\_bts\_dev[30] & 1.0 & 7292 & -0.1 & 0.0 & -0.1 & -0.1 & -0.0 \\ 
  sel\_a50\_bts\_dev[31] & 1.0 & 8664 & -0.0 & 0.0 & -0.1 & -0.0 & 0.0 \\ 
  sel\_a50\_bts\_dev[32] & 1.0 & 7704 & -0.1 & 0.0 & -0.1 & -0.1 & -0.0 \\ 
  sel\_a50\_bts\_dev[33] & 1.0 & 7076 & -0.1 & 0.0 & -0.2 & -0.1 & -0.1 \\ 
  sel\_a50\_bts\_dev[34] & 1.0 & 8034 & -0.2 & 0.0 & -0.2 & -0.2 & -0.1 \\ 
  sel\_a50\_bts\_dev[35] & 1.0 & 8503 & -0.1 & 0.0 & -0.2 & -0.1 & -0.0 \\ 
  sel\_a50\_bts\_dev[36] & 1.0 & 5889 & -0.1 & 0.0 & -0.1 & -0.1 & 0.0 \\ 
  sel\_a50\_bts\_dev[37] & 1.0 & 8628 & 0.2 & 0.0 & 0.1 & 0.2 & 0.3 \\ 
  sel\_a50\_bts\_dev[38] & 1.0 & 12000 & -0.0 & 0.0 & -0.1 & -0.0 & 0.1 \\ 
  sel\_a50\_bts\_dev[39] & 1.0 & 7902 & 0.1 & 0.1 & -0.1 & 0.1 & 0.2 \\ 
  sel\_a50\_bts\_dev[40] & 1.0 & 4660 & 0.1 & 0.0 & 0.0 & 0.1 & 0.2 \\ 
  sel\_a50\_bts\_dev[41] & 1.0 & 4686 & 0.0 & 0.1 & -0.1 & 0.0 & 0.1 \\ 
  sel\_a50\_bts\_dev[42] & 1.0 & 4470 & 0.2 & 0.1 & 0.1 & 0.2 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[1] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[2] & 1.0 & 12000 & -0.0 & 0.1 & -0.3 & -0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[3] & 1.0 & 12000 & 0.1 & 0.1 & -0.2 & 0.1 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[4] & 1.0 & 12000 & -0.2 & 0.1 & -0.4 & -0.2 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[5] & 1.0 & 12000 & -0.4 & 0.1 & -0.6 & -0.4 & -0.1 \\ 
  sel\_age\_one\_bts\_dev[6] & 1.0 & 12000 & -0.2 & 0.2 & -0.5 & -0.2 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[7] & 1.0 & 12000 & -0.3 & 0.2 & -0.6 & -0.3 & 0.0 \\ 
  sel\_age\_one\_bts\_dev[8] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[9] & 1.0 & 12000 & 0.1 & 0.1 & -0.1 & 0.1 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[10] & 1.0 & 12000 & -0.2 & 0.1 & -0.4 & -0.2 & 0.0 \\ 
  sel\_age\_one\_bts\_dev[11] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[12] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[13] & 1.0 & 12000 & -0.1 & 0.1 & -0.4 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[14] & 1.0 & 12000 & -0.1 & 0.1 & -0.4 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[15] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.0 \\ 
  sel\_age\_one\_bts\_dev[16] & 1.0 & 12000 & -0.0 & 0.1 & -0.2 & -0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[17] & 1.0 & 12000 & 0.0 & 0.1 & -0.1 & 0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[18] & 1.0 & 12000 & 0.1 & 0.1 & -0.1 & 0.1 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[19] & 1.0 & 12000 & 0.2 & 0.1 & -0.0 & 0.2 & 0.4 \\ 
  sel\_age\_one\_bts\_dev[20] & 1.0 & 12000 & 0.1 & 0.1 & -0.1 & 0.1 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[21] & 1.0 & 12000 & 0.1 & 0.1 & -0.1 & 0.1 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[22] & 1.0 & 12000 & 0.2 & 0.1 & -0.0 & 0.2 & 0.4 \\ 
  sel\_age\_one\_bts\_dev[23] & 1.0 & 12000 & 0.1 & 0.1 & -0.2 & 0.1 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[24] & 1.0 & 12000 & -0.0 & 0.1 & -0.3 & -0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[25] & 1.0 & 12000 & -0.0 & 0.1 & -0.2 & -0.0 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[26] & 1.0 & 12000 & -0.0 & 0.1 & -0.2 & -0.0 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[27] & 1.0 & 12000 & 0.2 & 0.1 & -0.0 & 0.2 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[28] & 1.0 & 12000 & 0.3 & 0.1 & 0.2 & 0.3 & 0.5 \\ 
  sel\_age\_one\_bts\_dev[29] & 1.0 & 12000 & 0.3 & 0.1 & 0.1 & 0.3 & 0.5 \\ 
  sel\_age\_one\_bts\_dev[30] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.0 \\ 
  sel\_age\_one\_bts\_dev[31] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[32] & 1.0 & 12000 & 0.2 & 0.1 & 0.1 & 0.2 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[33] & 1.0 & 12000 & 0.1 & 0.1 & 0.0 & 0.1 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[34] & 1.0 & 12000 & 0.0 & 0.1 & -0.1 & 0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[35] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[36] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[37] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.1 \\ 
  sel\_age\_one\_bts\_dev[38] & 1.0 & 12000 & 0.2 & 0.1 & 0.1 & 0.2 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[39] & 1.0 & 12000 & 0.1 & 0.2 & -0.2 & 0.1 & 0.5 \\ 
  sel\_age\_one\_bts\_dev[40] & 1.0 & 12000 & 0.0 & 0.1 & -0.2 & 0.0 & 0.2 \\ 
  sel\_age\_one\_bts\_dev[41] & 1.0 & 12000 & 0.1 & 0.1 & -0.1 & 0.1 & 0.3 \\ 
  sel\_age\_one\_bts\_dev[42] & 1.0 & 12000 & 0.0 & 0.1 & -0.2 & 0.0 & 0.2 \\ 
  rec\_dev\_future[1] & 1.0 & 12000 & 0.0 & 0.7 & -1.4 & 0.0 & 1.3 \\ 
  rec\_dev\_future[2] & 1.0 & 12000 & -0.0 & 0.7 & -1.4 & -0.0 & 1.3 \\ 
  rec\_dev\_future[3] & 1.0 & 12000 & -0.0 & 0.7 & -1.4 & -0.0 & 1.3 \\ 
  rec\_dev\_future[4] & 1.0 & 12000 & -0.0 & 0.7 & -1.3 & -0.0 & 1.3 \\ 
  rec\_dev\_future[5] & 1.0 & 12000 & -0.0 & 0.7 & -1.4 & 0.0 & 1.3 \\ 
  L1 & 1.0 & 9474 & 28.3 & 0.0 & 28.3 & 28.3 & 28.4 \\ 
  L2 & 1.0 & 9260 & 45.8 & 0.1 & 45.6 & 45.8 & 46.1 \\ 
  log\_K & 1.0 & 8516 & -0.1 & 0.0 & -0.1 & -0.1 & -0.1 \\ 
  d\_scale[1] & 1.0 & 12000 & 0.5 & 0.0 & 0.5 & 0.5 & 0.6 \\ 
  d\_scale[2] & 1.0 & 12000 & 0.7 & 0.0 & 0.7 & 0.7 & 0.7 \\ 
  d\_scale[3] & 1.0 & 12000 & 0.8 & 0.0 & 0.7 & 0.8 & 0.8 \\ 
  d\_scale[4] & 1.0 & 12000 & 0.8 & 0.0 & 0.8 & 0.8 & 0.9 \\ 
  d\_scale[5] & 1.0 & 12000 & 0.9 & 0.0 & 0.8 & 0.9 & 0.9 \\ 
  d\_scale[6] & 1.0 & 12000 & 0.9 & 0.0 & 0.9 & 0.9 & 1.0 \\ 
  d\_scale[7] & 1.0 & 12000 & 1.0 & 0.0 & 0.9 & 1.0 & 1.0 \\ 
  d\_scale[8] & 1.0 & 12000 & 1.0 & 0.0 & 0.9 & 1.0 & 1.0 \\ 
  d\_scale[9] & 1.0 & 12000 & 1.0 & 0.0 & 1.0 & 1.0 & 1.0 \\ 
  d\_scale[10] & 1.0 & 12000 & 0.9 & 0.0 & 0.9 & 0.9 & 1.0 \\ 
  d\_scale[11] & 1.0 & 12000 & 1.0 & 0.0 & 0.9 & 1.0 & 1.0 \\ 
  d\_scale[12] & 1.0 & 12000 & 0.9 & 0.0 & 0.8 & 0.9 & 0.9 \\ 
  d\_scale[13] & 1.0 & 12000 & 1.0 & 0.0 & 1.0 & 1.0 & 1.1 \\ 
  coh\_eff[1] & 1.0 & 12000 & 0.0 & 1.0 & -2.0 & 0.0 & 2.0 \\ 
  coh\_eff[2] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  coh\_eff[3] & 1.0 & 12000 & 0.0 & 1.0 & -1.9 & -0.0 & 2.0 \\ 
  coh\_eff[4] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  coh\_eff[5] & 1.0 & 12000 & 0.0 & 1.0 & -2.0 & 0.0 & 2.0 \\ 
  coh\_eff[6] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  coh\_eff[7] & 1.0 & 12000 & -0.0 & 1.0 & -1.9 & 0.0 & 1.9 \\ 
  coh\_eff[8] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & 0.0 & 1.9 \\ 
  coh\_eff[9] & 1.0 & 12000 & 0.0 & 1.0 & -1.9 & 0.0 & 1.9 \\ 
  coh\_eff[10] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & 0.0 & 1.9 \\ 
  coh\_eff[11] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & 0.0 & 2.0 \\ 
  coh\_eff[12] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  coh\_eff[13] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  coh\_eff[14] & 1.0 & 12000 & 0.0 & 1.0 & -2.0 & 0.0 & 2.0 \\ 
  coh\_eff[15] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 1.9 \\ 
  coh\_eff[16] & 1.0 & 12000 & 0.0 & 1.0 & -1.9 & 0.0 & 2.0 \\ 
  coh\_eff[17] & 1.0 & 12000 & -0.2 & 1.0 & -2.1 & -0.2 & 1.7 \\ 
  coh\_eff[18] & 1.0 & 12000 & 0.3 & 1.0 & -1.7 & 0.3 & 2.2 \\ 
  coh\_eff[19] & 1.0 & 12000 & 0.0 & 1.0 & -1.9 & 0.0 & 2.0 \\ 
  coh\_eff[20] & 1.0 & 12000 & 0.6 & 1.0 & -1.3 & 0.6 & 2.5 \\ 
  coh\_eff[21] & 1.0 & 12000 & -0.4 & 0.9 & -2.2 & -0.4 & 1.4 \\ 
  coh\_eff[22] & 1.0 & 12000 & 0.7 & 0.9 & -1.2 & 0.7 & 2.5 \\ 
  coh\_eff[23] & 1.0 & 12000 & -0.6 & 0.9 & -2.3 & -0.6 & 1.1 \\ 
  coh\_eff[24] & 1.0 & 12000 & 0.4 & 0.9 & -1.3 & 0.5 & 2.1 \\ 
  coh\_eff[25] & 1.0 & 12000 & 0.0 & 0.9 & -1.7 & 0.0 & 1.7 \\ 
  coh\_eff[26] & 1.0 & 12000 & -0.1 & 0.8 & -1.8 & -0.1 & 1.4 \\ 
  coh\_eff[27] & 1.0 & 12000 & -0.6 & 0.7 & -2.1 & -0.5 & 0.8 \\ 
  coh\_eff[28] & 1.0 & 12000 & -0.7 & 0.5 & -1.7 & -0.7 & 0.2 \\ 
  coh\_eff[29] & 1.0 & 12000 & 0.5 & 0.4 & -0.4 & 0.5 & 1.3 \\ 
  coh\_eff[30] & 1.0 & 12000 & 0.6 & 0.5 & -0.4 & 0.6 & 1.4 \\ 
  coh\_eff[31] & 1.0 & 12000 & 1.0 & 0.4 & 0.2 & 1.0 & 1.7 \\ 
  coh\_eff[32] & 1.0 & 12000 & -0.2 & 0.4 & -1.0 & -0.2 & 0.6 \\ 
  coh\_eff[33] & 1.0 & 12000 & 0.5 & 0.4 & -0.3 & 0.5 & 1.2 \\ 
  coh\_eff[34] & 1.0 & 12000 & -0.1 & 0.4 & -1.0 & -0.1 & 0.6 \\ 
  coh\_eff[35] & 1.0 & 12000 & -1.1 & 0.4 & -2.0 & -1.1 & -0.3 \\ 
  coh\_eff[36] & 1.0 & 9859 & -1.0 & 0.4 & -1.9 & -1.0 & -0.2 \\ 
  coh\_eff[37] & 1.0 & 12000 & -1.1 & 0.3 & -1.6 & -1.0 & -0.5 \\ 
  coh\_eff[38] & 1.0 & 10221 & 0.8 & 0.2 & 0.4 & 0.8 & 1.2 \\ 
  coh\_eff[39] & 1.0 & 12000 & 1.8 & 0.1 & 1.6 & 1.8 & 2.0 \\ 
  coh\_eff[40] & 1.0 & 12000 & 0.4 & 0.2 & 0.0 & 0.5 & 0.8 \\ 
  coh\_eff[41] & 1.0 & 12000 & -1.1 & 0.2 & -1.6 & -1.1 & -0.7 \\ 
  coh\_eff[42] & 1.0 & 9852 & -0.2 & 0.2 & -0.6 & -0.2 & 0.3 \\ 
  coh\_eff[43] & 1.0 & 12000 & 0.9 & 0.2 & 0.5 & 0.9 & 1.3 \\ 
  coh\_eff[44] & 1.0 & 12000 & 0.4 & 0.1 & 0.1 & 0.4 & 0.7 \\ 
  coh\_eff[45] & 1.0 & 12000 & 0.4 & 0.1 & 0.2 & 0.4 & 0.5 \\ 
  coh\_eff[46] & 1.0 & 12000 & -0.1 & 0.2 & -0.5 & -0.1 & 0.2 \\ 
  coh\_eff[47] & 1.0 & 12000 & 0.3 & 0.2 & 0.0 & 0.3 & 0.6 \\ 
  coh\_eff[48] & 1.0 & 12000 & 0.8 & 0.1 & 0.6 & 0.8 & 1.1 \\ 
  coh\_eff[49] & 1.0 & 12000 & 1.5 & 0.1 & 1.3 & 1.5 & 1.6 \\ 
  coh\_eff[50] & 1.0 & 12000 & 0.4 & 0.1 & 0.1 & 0.4 & 0.6 \\ 
  coh\_eff[51] & 1.0 & 12000 & -0.9 & 0.2 & -1.2 & -0.9 & -0.6 \\ 
  coh\_eff[52] & 1.0 & 12000 & -1.2 & 0.2 & -1.6 & -1.2 & -0.9 \\ 
  coh\_eff[53] & 1.0 & 12000 & -0.5 & 0.2 & -0.8 & -0.5 & -0.2 \\ 
  coh\_eff[54] & 1.0 & 12000 & -1.8 & 0.2 & -2.2 & -1.8 & -1.5 \\ 
  coh\_eff[55] & 1.0 & 12000 & -0.8 & 0.1 & -1.1 & -0.8 & -0.6 \\ 
  coh\_eff[56] & 1.0 & 12000 & -1.6 & 0.2 & -2.1 & -1.6 & -1.2 \\ 
  coh\_eff[57] & 1.0 & 11527 & -2.1 & 0.2 & -2.5 & -2.1 & -1.8 \\ 
  coh\_eff[58] & 1.0 & 12000 & -2.0 & 0.1 & -2.3 & -2.0 & -1.8 \\ 
  coh\_eff[59] & 1.0 & 12000 & -1.3 & 0.1 & -1.5 & -1.3 & -1.0 \\ 
  coh\_eff[60] & 1.0 & 12000 & 0.7 & 0.1 & 0.5 & 0.7 & 0.9 \\ 
  coh\_eff[61] & 1.0 & 11414 & 0.8 & 0.1 & 0.6 & 0.8 & 0.9 \\ 
  coh\_eff[62] & 1.0 & 12000 & -0.0 & 0.1 & -0.2 & -0.0 & 0.1 \\ 
  coh\_eff[63] & 1.0 & 12000 & 0.3 & 0.1 & 0.0 & 0.3 & 0.5 \\ 
  coh\_eff[64] & 1.0 & 12000 & 0.4 & 0.2 & 0.0 & 0.4 & 0.8 \\ 
  coh\_eff[65] & 1.0 & 12000 & 1.4 & 0.2 & 1.0 & 1.4 & 1.7 \\ 
  coh\_eff[66] & 1.0 & 12000 & 0.4 & 0.2 & 0.0 & 0.4 & 0.7 \\ 
  coh\_eff[67] & 1.0 & 12000 & 0.2 & 0.0 & 0.1 & 0.2 & 0.3 \\ 
  coh\_eff[68] & 1.0 & 12000 & 1.0 & 0.1 & 0.7 & 1.0 & 1.3 \\ 
  coh\_eff[69] & 1.0 & 12000 & 0.1 & 1.0 & -1.8 & 0.1 & 2.1 \\ 
  coh\_eff[70] & 1.0 & 12000 & 0.0 & 1.0 & -1.9 & 0.0 & 1.9 \\ 
  coh\_eff[71] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 1.9 \\ 
  yr\_eff[1] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & 0.0 & 2.0 \\ 
  yr\_eff[2] & 1.0 & 12000 & 0.2 & 1.0 & -1.8 & 0.2 & 2.2 \\ 
  yr\_eff[3] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 1.9 \\ 
  yr\_eff[4] & 1.0 & 12000 & 0.2 & 1.0 & -1.7 & 0.3 & 2.1 \\ 
  yr\_eff[5] & 1.0 & 12000 & 0.3 & 1.0 & -1.7 & 0.3 & 2.2 \\ 
  yr\_eff[6] & 1.0 & 12000 & 1.2 & 1.0 & -0.9 & 1.3 & 3.0 \\ 
  yr\_eff[7] & 1.0 & 12000 & 0.4 & 0.9 & -1.5 & 0.5 & 2.2 \\ 
  yr\_eff[8] & 1.0 & 12000 & 1.8 & 0.8 & -0.0 & 1.9 & 3.1 \\ 
  yr\_eff[9] & 1.0 & 12000 & 0.4 & 0.9 & -1.5 & 0.4 & 2.0 \\ 
  yr\_eff[10] & 1.0 & 12000 & 1.0 & 0.8 & -0.8 & 1.1 & 2.4 \\ 
  yr\_eff[11] & 1.0 & 10859 & 1.1 & 0.8 & -0.7 & 1.1 & 2.4 \\ 
  yr\_eff[12] & 1.0 & 10744 & 0.8 & 0.8 & -0.9 & 0.8 & 2.0 \\ 
  yr\_eff[13] & 1.0 & 11765 & -0.0 & 0.7 & -1.6 & 0.0 & 1.2 \\ 
  yr\_eff[14] & 1.0 & 12000 & 0.8 & 0.4 & -0.2 & 0.8 & 1.5 \\ 
  yr\_eff[15] & 1.0 & 12000 & -0.7 & 0.6 & -2.0 & -0.7 & 0.3 \\ 
  yr\_eff[16] & 1.0 & 10746 & -0.1 & 0.5 & -1.2 & -0.0 & 0.8 \\ 
  yr\_eff[17] & 1.0 & 12000 & -1.6 & 0.6 & -3.0 & -1.6 & -0.5 \\ 
  yr\_eff[18] & 1.0 & 12000 & -0.8 & 0.6 & -2.0 & -0.8 & 0.2 \\ 
  yr\_eff[19] & 1.0 & 12000 & -1.2 & 0.6 & -2.5 & -1.2 & -0.1 \\ 
  yr\_eff[20] & 1.0 & 12000 & -1.0 & 0.6 & -2.2 & -0.9 & 0.1 \\ 
  yr\_eff[21] & 1.0 & 10093 & 0.4 & 0.4 & -0.5 & 0.4 & 1.1 \\ 
  yr\_eff[22] & 1.0 & 9673 & -0.0 & 0.4 & -0.8 & 0.0 & 0.7 \\ 
  yr\_eff[23] & 1.0 & 12000 & 0.1 & 0.2 & -0.4 & 0.1 & 0.5 \\ 
  yr\_eff[24] & 1.0 & 9975 & 1.0 & 0.2 & 0.6 & 1.0 & 1.3 \\ 
  yr\_eff[25] & 1.0 & 12000 & -0.1 & 0.1 & -0.3 & -0.1 & 0.2 \\ 
  yr\_eff[26] & 1.0 & 12000 & -0.5 & 0.2 & -1.0 & -0.5 & -0.1 \\ 
  yr\_eff[27] & 1.0 & 12000 & -0.8 & 0.3 & -1.4 & -0.8 & -0.3 \\ 
  yr\_eff[28] & 1.0 & 9721 & -0.3 & 0.3 & -0.9 & -0.3 & 0.2 \\ 
  yr\_eff[29] & 1.0 & 12000 & -0.7 & 0.3 & -1.2 & -0.7 & -0.2 \\ 
  yr\_eff[30] & 1.0 & 12000 & -0.4 & 0.2 & -0.8 & -0.4 & -0.1 \\ 
  yr\_eff[31] & 1.0 & 12000 & -0.4 & 0.1 & -0.6 & -0.4 & -0.1 \\ 
  yr\_eff[32] & 1.0 & 12000 & 0.5 & 0.1 & 0.3 & 0.5 & 0.8 \\ 
  yr\_eff[33] & 1.0 & 9860 & -0.1 & 0.2 & -0.4 & -0.1 & 0.2 \\ 
  yr\_eff[34] & 1.0 & 12000 & -0.2 & 0.2 & -0.5 & -0.2 & 0.1 \\ 
  yr\_eff[35] & 1.0 & 10970 & -0.5 & 0.2 & -0.8 & -0.5 & -0.2 \\ 
  yr\_eff[36] & 1.0 & 11247 & -1.0 & 0.2 & -1.4 & -1.0 & -0.6 \\ 
  yr\_eff[37] & 1.0 & 10467 & -0.2 & 0.2 & -0.5 & -0.2 & 0.1 \\ 
  yr\_eff[38] & 1.0 & 12000 & 1.0 & 0.1 & 0.8 & 1.0 & 1.2 \\ 
  yr\_eff[39] & 1.0 & 12000 & 0.4 & 0.1 & 0.1 & 0.4 & 0.6 \\ 
  yr\_eff[40] & 1.0 & 12000 & 1.6 & 0.1 & 1.4 & 1.6 & 1.7 \\ 
  yr\_eff[41] & 1.0 & 10962 & 0.6 & 0.1 & 0.4 & 0.6 & 0.8 \\ 
  yr\_eff[42] & 1.0 & 12000 & 0.8 & 0.1 & 0.5 & 0.8 & 1.0 \\ 
  yr\_eff[43] & 1.0 & 10726 & 0.0 & 0.1 & -0.2 & 0.0 & 0.3 \\ 
  yr\_eff[44] & 1.0 & 11175 & 0.5 & 0.1 & 0.3 & 0.5 & 0.7 \\ 
  yr\_eff[45] & 1.0 & 12000 & 0.7 & 0.1 & 0.5 & 0.7 & 0.8 \\ 
  yr\_eff[46] & 1.0 & 12000 & -2.5 & 0.3 & -3.1 & -2.5 & -2.0 \\ 
  yr\_eff[47] & 1.0 & 11394 & -0.5 & 0.1 & -0.7 & -0.5 & -0.3 \\ 
  yr\_eff[48] & 1.0 & 12000 & -0.2 & 0.1 & -0.4 & -0.2 & -0.0 \\ 
  yr\_eff[49] & 1.0 & 12000 & -1.1 & 0.2 & -1.5 & -1.1 & -0.8 \\ 
  yr\_eff[50] & 1.0 & 12000 & 0.8 & 0.1 & 0.6 & 0.8 & 1.0 \\ 
  yr\_eff[51] & 1.0 & 12000 & -2.0 & 0.3 & -2.5 & -2.0 & -1.5 \\ 
  yr\_eff[52] & 1.0 & 12000 & -1.9 & 0.3 & -2.4 & -1.9 & -1.4 \\ 
  yr\_eff[53] & 1.0 & 12000 & -0.2 & 0.1 & -0.4 & -0.2 & -0.1 \\ 
  yr\_eff[54] & 1.0 & 12000 & 0.3 & 0.8 & -1.5 & 0.3 & 1.8 \\ 
  yr\_eff[55] & 1.0 & 12000 & 0.0 & 1.0 & -2.0 & 0.0 & 2.0 \\ 
  yr\_eff[56] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  yr\_eff[57] & 1.0 & 12000 & 0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  yr\_eff[58] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  yr\_eff[59] & 1.0 & 12000 & -0.0 & 1.0 & -2.0 & -0.0 & 2.0 \\ 
  log-posterior & 1.0 & 4058 & -5813.1 & 26.2 & -5865.6 & -5812.4 & -5763.7 \\ 
  \hline
\end{tabular}
\end{table}

# Main data file
\fontsize{3}{4}
```{r eval = TRUE, include=TRUE,echo=FALSE, comment=NA }
ts <- readLines("../2023_runs/dat/pm_23.8.dat")
for (i in 1:length(ts)) cat(ts[i], "\n")
```
