---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
    template: ms.tex
    includes:
            in_header: mystyles.sty
title: "EBS pollock stock assessment 2017"
thanks: "Replication files are available on the author's Github account..."
author:
- name: James Ianelli   
  affiliation: Alaska Fisheries Science center
- name: Taina Honkalehto
  affiliation: Alaska Fisheries Science center
abstract: "This document provides an introduction to R Markdown, argues for its..."
keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: ~/Dropbox/master.bib
biblio-style: apsr
---


```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.width = 12, fig.height = 7, echo = FALSE, warning = FALSE, message = FALSE, cache=FALSE,results="asis")
library(xtable)
options(xtable.comment = FALSE)
library(tidyverse)
library(PBSadmb,quietly=TRUE,verbose=FALSE)
#include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
#echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
#message = FALSE prevents messages that are generated by code from appearing in the finished file.
#warning = FALSE prevents warnings that are generated by code from appearing in the finished.
#fig.cap = "..." adds a caption to graphical results.
#To set global options that apply to every chunk in your file, call knitr::opts_chunk$set in a code chunk. Knitr will treat each option that you pass to 
thisyr    = 2017
lastyr    = thisyr-1
nextyr    = thisyr+1

# The model specs
mod_names <- c("2016 Model",
  "2016 update ",
  "2016 biomass ")
.MODELDIR = c(
  "../runs/16.1/", 
  "../runs/16.1a/") 
.THEME    = theme_bw(base_size = 11, base_family = "")
.OVERLAY  = TRUE

fc  <- (read_csv("data/fig_captions.csv"))
figcap <- fc$cap
figlab <- fc$label
reffig <- function(i){ print(paste0("\ref{fig:",figlab[i],"}")) }  
reffig(2)
tmp <- "catch.png"
printfig <- function(tmp,i){
cat(paste0("![",figcap[i],"\\label{fig:",figlab[i],"}](figs/",tmp,")  \n\n"))
} 
printfig(tmp,1)

tc  <- (read_csv("data/table_captions.csv"))
tabcap <- tc$cap
tablab <- tc$label
tap <- data_frame(t=c(1,2),c=c(1,2))
#i   <- 1
#tab <- xtable(tmp, digits=0, auto=TRUE,caption = tabcap[i], label = paste0("tab:",tablab[i]) ); print(tab, caption.placement = "top", include.rownames = FALSE, sanitize.text.function = function(x){x})
#for (i in seq_along(tabcap))
printtab <- function(tmp,i){tab <- xtable(tmp, digits=0, auto=TRUE,caption = tabcap[i], label = paste0("tab:",tablab[i])); print(tab, caption.placement = "top", include.rownames = FALSE, sanitize.text.function = function(x){x}) } 
reftab <- function(i){ print(paste0("tab:",tablab[i])) }  
printtab(tap,1)
reftab(1)
# for (i in seq_along(tabcap)) reftab(i)
```

```{r child = 'text.Rmd'}

```

```{r child = 'figs.Rmd'}

```

```{r child = 'tab.Rmd'}

```

```{r child = 'model.Rmd'}

```
