# Executive summary

This chapter covers the Eastern Bering Sea (EBS) region—the Aleutian Islands
region (Chapter 1A) and the Bogoslof Island area (Chapter 1B) are presented
separately. A multi-species stock assessment (e.g., from [2020](https://apps-afsc.fisheries.noaa.gov/refm/docs/2020/EBSmultispp.pdf)).

### Summary of changes in assessment inputs

Relative to last year’s BSAI SAFE report, the following substantive changes have been made in the EBS pollock stock
assessment. This includes the `r thisyr` NMFS bottom-trawl survey (BTS) covering the EBS and NBS. As before, these
data were treated with a spatio temporal model for index standardization; however, this year a number of refinements from the 2019 index
were made which changed the time series used for tuning the assessment.
The BTS chartered boats also collected acoustic data and the series  was updated this year (AVO).  

#### Changes in the data

   1.  Observer data for catch-at-age and average weight-at-age from
   the `r lastyr` fishery were finalized and included. 

   2.  Total catch as reported by NMFS Alaska Regional office was updated and included through `r thisyr`.
   
   3.  In summer `r thisyr`, the AFSC conducted the bottom trawl survey in the EBS and extended into the NBS.
   A VAST model evaluation (including the cold-pool extent) was used as the main index.

   3.  The bottom trawl survey collected acoustic data opportunistically and extend the index from 2006-2019 and again this year.

   3.  Because of indications of smaller-than usual fish apparent in the 2021 fishery, length composition data from this year's fishery, along with 
  a preliminary estimate of the catch-age composition for this year was used.

### Changes in the assessment methods

There were some minor changes to data used for the assessment model this year to accommodate requests 
from the SSC and Plan Team. 

## Summary of EBS pollock results
The following table applies for Model 20.0, the model used for last year's assessment 
An alternative table is provided xxxx.
As in past years, the ABC recommendation reflects the Tier 3 estimate.

\begin{table}[ht]
\centering
\begin{tabular}{lrr|rr}
  \hline
       & \multicolumn{2}{c|}{As estimated or $\mathit{specified}$ } & \multicolumn{2}{c}{As estimated or $\mathit{recommended}$ }  \\
       & \multicolumn{2}{c|}{$\mathit{last}$ year for:}  & \multicolumn{2}{c}{$\mathit{this}$ year for: }               \\
        Quantity & `r thisyr`      &`r thisyr+1`   & `r thisyr+1`      &`r thisyr+2` \\ 
  \hline
  M            (natural mortality rate, ages 3+)	&	0.3	&	0.3	&	0.3	&	0.3 \\
  Tier         &	1a	&	1a	&	1a	&	1a \\
  Projected    total (age  3+) biomass (t)     & `r M$it$a1[1]` t & `r M$it$a2[1]` t & `r  M$age3plus1s` t & `r  M$age3plus2s` t \\
  Projected    female  spawning  biomass (t)   & `r M$it$b1[1]` t & `r M$it$b2[1]` t & `r  M$ssb1s`  t & `r  M$ssb2s`  t \\  
  $B_0$        & `r M$it$c1[1]` t & `r M$it$c2[1]` t & `r  M$b0s`,000  t & `r  M$b0s`,000  t \\          
  $B_{msy}$    & `r M$it$d1[1]` t & `r M$it$d2[1]` t & `r  M$bmsys`,000  t & `r  M$bmsys`,000  t \\          
  $F_{OFL}$    & `r M$it[1,8]` & `r M$it[2,8]` & `r  round(M$arithmeanF,3)`  & `r  round(M$arithmeanF,3)`  \\                  
  $maxF_{ABC}$ & `r M$it[1,9]` & `r M$it[2,9]` & `r  round(M$harmeanF,3)`  & `r  round(M$harmeanF,3)`  \\                  
  $F_{ABC}$    & `r M$it[1,10]`& `r M$it[2,10]`& `r  (M$fabc1)` & `r  (M$fabc2)` \\                  
  $OFL$        & `r M$it$e1[1]` t & `r M$it$e2[1]` t & `r  M$ofl1s`  t & `r  M$ofl2s`  t \\          
  $maxABC$     & `r M$it$f1[1]` t & `r M$it$f2[1]` t & `r  M$maxabc1s  ` t & `r  M$maxabc2s  ` t \\      
  $ABC$        & `r M$it$g1[1]` t & `r M$it$g2[1]` t & `r  M$abc1s ` t & `r  M$abc2s`  t \\        
  \hline
  Status	                              &	`r lastyr-1`  & `r lastyr`&			`r lastyr`             &	`r thisyr`          \\
  \hline
  Overfishing	                          &	No	        &	n/a	      &	No	                       &	n/a                 \\
  Overfished	                          &	n/a	        &	No	      &	n/a	                       &	No                  \\
  Approaching overfished	              &	n/a	        &	No	      &	n/a	                       &	No                  \\
  \hline
\end{tabular}
\end{table}

## Response to SSC and Plan Team comments

### General comments

_From several SSC comments in the past few years related reviewiing the support for retaining the EBS Pollock assessment in Tier 1 
versus reclassifying it as Tier 3._

  * Consideration of whether the observed sensitivity in the SRR to prior specification should
constitute an increased risk level specification within the assessment or population dynamics related
considerations. This could provide a clearer justification for the use of the Tier 3 calculation as
the basis for harvest specification.     

    - _We evaluated factors affecting the Tier classification in the 2020 assessment and showed that the 
priors used reflect the SRR curve were conservative and justified based on residual patterns near the origin (as 
opposed to alternatives that fit data on the descending slope of the Ricker SRR._


  * The SSC recommends that if the assessment is considered in the appropriate Tier, buffers should be based on     
the use of the Risk Table rather than the continued use of Tier 3 calculations for a Tier 1 stock.

    - _We agree in principle, and the second part of applying the risk table approach would be to specify a buffer. 
  One logical application of the buffer would be to use the ratio of the Tier 3 ABC divided by the Tier 1 value (which would result in a 
recommended ABC equal to Tier 3)._

  * The SSC also notes that this stock may be a candidate for the infrequently used Tier 2
classification. This tier uses the SR relationship for stock status and OFL, but uses the ratio of SPR rates for adjustments when the 
stock is below $B_{MSY}$.

    - _An examination of Tier 2 as an option resulted in a value of `r M$Tier2_ABC1s ` t (or a hybrid of Tier 1 and 2 of 
`r M$Tier1.5_ABC1s` t for 2022 ABC values. We note that selecting Tier 2 would require similar reliance on the SRR estimates
and impact on fishing rate values._         

---


**The SSC had a number of recommendations for additional research supporting this assessment:**

**From previous requests:**

The SSC had encouraged further investigation of the apparent shift between a clear 2012 year-class to mixed 2012-2013 
year classes in the data, suggestive of potentially variable ageing bias.   

  - _The fishery and survey age data shows a similar relative proportion of these two year classes. This year we present a spatial map of where these
		year classes have appeared and note that there appears to be some separation in their average locations. This could indicate that the year-classes
		may have had sufficient separation to minimize spatial overlap and exposure to cannibalism._

The work in deriving an external estimate of temporal variability in catchability for the bottom trawl survey (relative to the acoustic survey) due to vertical availability, 
the SSC noted that catchability would logically also vary for the acoustic survey. The SSC encourages 
further work to develop the simultaneous modelling of these two surveys, accounting for vertical and distributional 
shifts (including into the northern Bering Sea survey area; NBS). When
sufficiently explored, the SSC looks forward to assessment model configurations that explore the
use of a time-series from this method.  

  - _Work on this topic stalled as analysts focused their efforts on methods to incorporate the uncrewed surface 
  vessels (USVs) to collect acoustic data in 2020. We anticipate this work to be pursued when the planned 2022 acoustic-trawl survey become available._

The SSC supports ongoing genetic studies to determine the relationship between pollock in the NBS and EBS,  as well as other surrounding regions (AI, GOA).  

  - _Some preliminary results showing the main genetic population components are presented below. Indications are 
  that there is a high degree of separation of pollock from Japan compared to those sampled off of Alaska. Within
  Alaskan waters, the Bering Sea samples were relatively distinct from the Aleutian Islands and the Gulf of Alaska._

The SSC also looks forward to estimates of movement and abundance along the US-Russia EEZ 
boundary based on echosounders fixed to moorings in this area.     

  - _The moored sounders have been recovered in September 2020 but the data have yet to be processed._     

Re-examine the geographic subset of data currently used to develop the AVO
index, specifically to see if including Bristol Bay data improves the
correlation.    

  -  _Work on this continues and there are plans to refine the treatment of AVO data relative to the full  acoustic-trawl survey
		slated for 2022._     

Given the apparent disappearance of the second and large mode in fishery length compositions as
the 2020 B-season progressed, exploration of within-season spatial variation in fishery length
composition would be useful in evaluating whether these larger pollock simply moved out of the area
of fishing effort, or died as a result of natural or fishing mortality.

  - _Because of this concern, we re-estimated the length-at-age values in order to include the 
  2021 fishery data (conventionally, aspects of the current-year age structure of fishing is unavailable
until samples can be returned from NMFS observers and aged). We also constructed a global age-length key
to supplement age composition information from the 2021 fishery._

From October 2021 (unless covered above): 

The SSC provides a clarification that it is requesting a description of the method used for
projecting selectivity when calculating the OFL/ABC and looks forward to a retrospective analysis on
the performance of this projection method relative to the subsequently estimated selectivity in the
next assessment. This request was motivated by the large change in FOFL observed from the 2019 to
2020 assessments.

  -  _These estimates are compared from the retrospective runs in addition to a review of how
   recent selectivity estimates impact $F_{MSY}$ rates._

\pagebreak

# Introduction

## General

Walleye pollock (_Gadus chalcogrammus_; hereafter referred to as pollock) are
broadly distributed throughout the North Pacific with the largest
concentrations found in the Eastern Bering Sea. Also  known as
Alaska pollock, this species continues to play important roles ecologically
and economically.

## Review of Life History
In the EBS pollock spawn generally in the period
March-May and in relatively localized regions during specific periods (Bailey
2000). Generally spawning begins nearshore north of Unimak Island in March and
April and later near the Pribilof Islands (Jung et al. 2006, Bacheler et al.
2010). Females are batch spawners with up to 10 batches of eggs per female per
year. Eggs and larvae of EBS pollock are planktonic for a period of about 90
days and appear to be sensitive to environmental conditions. These conditions
likely affect their dispersal into favorable areas (for subsequent separation
from predators) and also affect general food requirements for over-wintering
survival (Gann et al. 2015, Heintz et al., 2013, Hunt et al. 2011, 
Ciannelli et al. 2004). Duffy-Anderson et al. (2015) provide a
review of the early life history of EBS pollock.

Throughout their range juvenile pollock feed on a variety of planktonic
crustaceans,  including calanoid copepods and euphausiids. In the EBS shelf
region, one-year-old pollock are found throughout the water column, but also
commonly occur in the NMFS bottom trawl survey. Ages 2 and 3 year old pollock
are rarely caught in summer bottom trawl survey gear and are more common in
the  midwater zone as detected by mid-water acoustic trawl surveys. Younger
pollock are  generally found in the more northern parts of the survey area and
appear to move to the southeast as they age (Buckley et al. 2009).
Euphausiids, principally _Thysanoessa inermis_ and _T. raschii_, are among the
most important prey items for pollock in the Bering Sea (Livingston, 1991;
Lang et al., 2000; Brodeur et al., 2002; Cianelli et al., 2004; Lang et al.,
2005).  Pollock diets become more piscivorous with age, and cannibalism has
been commonly observed in this region. However, Buckley et al. (2016) showed
spatial patterns of pollock foraging by size of predators. For example, the
northern part of the shelf region between the 100 and 200 m isobaths
(closest to the shelf break) tends to be more piscivorous than counterparts in
other areas.


## Stock structure
Genetic samples were taken from pollock and collections have continued from sources including
observers and AFSC research surveys. A large study using whole genome sequencing is currently
underway for samples of walleye pollock from Zhemchug Canyon, Japan, Prince William Sound, Bogoslof,
Shelikof, and the Northern Bering Sea. This project is a collaboration between the Joint Institute
for the Study of Atmosphere and Oceans (currently CICOES, the Cooperative Institute for Climate,
Ocean, and Ecosystem Science) and the Alaska Fisheries Science Center Cooperative Research Program.
The goals of the project include investigating whether genetic stock structure exists in walleye
pollock, if these patterns are temporally stable, and if distributional shifts under climate change
are detectable using genomic data. Whole genome sequencing is a new approach to the study of pollock
stock structure that is expected to yield higher statistical power than previous results using
microsatellite DNA markers. This team \footnote{   Eleni Petrou, Eleanor Bors, Lorenz Hauser, and
Ingrid Spies } sequenced 617 pollock collected from Japan, the Bering Sea, Chukchi Sea, Aleutian
Islands, Alaska Peninsula, and Gulf of Alaska using low-coverage whole genome sequencing. They
identified 5,316,997 single nucleotide polymorphisms (i.e., sites in the genome with genetic
variation) that were genotyped in more than 70% of samples and had a minor allele frequency of more
than 0.05. To visualize genetic differences between samples, they conducted principal components
analysis (PCA) using all samples and found that samples from Japan were highly distinct. A separate PCA was
run with Japan excluded showed a “three stripe” pattern (Fig. \ref{fig:PCA_genetics}). 
In other systems, this pattern has been associated with the presence of chromosomal 
inversions, as homo- and heterokaryotypes for each inversion
polymorphism form distinct clusters in a PCA. Additional analyses are needed to test 
and quantify genetic population structure in pollock.

For management purposes, the preliminary conclusions from these genetics results are:
1) there is stock structure in pollock that appears to be stable through time and 2) Some aspect of stock
structure is latitudinal---Bering Sea pollock appear distinct from fish collected from the Gulf
of Alaska and the Aleutian Islands. The results appear strong enough that a GTseq panel could be
designed in the future to determine stock of origin of walleye pollock, the scale of which may be
relatively large, such as “Bering Sea” or “GOA”. The scope and funding sources for this project will be planned
in 2022 with sampling designs developed for implementation as early as 2023.

# Fishery  
## Description of the directed fishery 
Historically, EBS pollock catches were low until directed foreign fisheries
began in 1964. Catches increased rapidly during the late 1960s and reached a
peak in 1970--75 when they ranged from 1.3 to 1.9 million t annually.
Following the peak catch in 1972, bilateral agreements with Japan and the USSR
resulted in reductions. During a 10-year period, catches by foreign vessels
operating in the “Donut Hole” region of the Aleutian Basin were substantial
totaling nearly 7 million t (Table \ref{tab:catch}).   A fishing moratorium
for this area was enacted in 1993 and only trace amounts of pollock have been
harvested from the Aleutian Basin region since then.  Since the late 1970s,
the average EBS pollock catch has been about 1.2 million t, ranging from 0.810
million t in 2009 to nearly 1.5 million t during 2003--2006 (Table
\ref{tab:catch}).  United States vessels began fishing for pollock in 1980 and
by 1987 they were able to take 99\% of the quota. Since 1988, U.S. flagged
vessels have been operating in this fishery.  The current observer program for
the domestic fishery formally began in 1991 and prior to that, observers were
deployed  aboard the foreign vessels since the late 1970s.  From the period
1991 to 2011 about 80\% of the catch was observed at sea or during dockside
offloading. Since 2011, regulations require that all vessels participating in
the pollock fishery carry at least one observer so nearly 100% of the pollock
fishing operations are monitored by scientifically trained observers.
Historical catch estimates used in the assessment, along with management
measures (i.e., ABCs and TACs) are shown in Table \ref{tab:abc_tac}. 


### Catch patterns
The \"A-season\" for directed EBS pollock fishing opens on January 20th and
fishing typically extends into early-mid April. During this season the fishery
targets pre-spawning pollock and produces pollock roe that, under optimal
conditions, can comprise over 4\% of the catch in weight. The summer, or
\"B-season\" presently opens on June 10th and fishing extends through noon on
November 1st. The A-season fishery concentrates primarily north and west of
Unimak Island depending on ice conditions and fish distribution. There has
also been effort along the 100m depth contour (and deeper) between Unimak
Island and the Pribilof Islands. The general pattern by season (and area) has
varied over time with recent B-season catches occurring in the southeast
portion of the shelf (east of 170$^\circ$W longitude; Fig. \ref{fig:catch}).
Since 2011, regulations and industry-based measures to reduce Chinook salmon
bycatch have affected the spatial distribution of the fishery and to some
degree, the way individual vessel operators fish (Stram and Ianelli, 2014). In 
2020, the fishing fleet encountered higher than normal bycatch of herring and this
has further constrained the fishing grounds due to area closures. Additionally,
sablefish appear to be highly abundant in the region and have comprised a significant
proportion of the incidental catches in the pollock fishery (proportionally still less
than 1% of the total landings). Comparing encounters of bycatch and pollock
relative to the effort (total duration of all tows) the pollock fleet
the Chinook salmon bycatch rate was relatively flat whereas the encounters with
sablefish were markedly higher (Fig. \ref{fig:fsh_psc_cpue}). 

The catch estimates by sex for the seasons indicate that over time, the number
of males and females has been fairly equal but in the period 2017-2020
the A-season catch of females has been slightly higher and conversely, in the B-season
there has been a slightly higher number of males taken (Fig. \ref{fig:catch_sex}). The
2021 A-season fishery spatial pattern had a relatively higher concentrations of
fishing near the Pribilof Islands and catches near Unimak and east compared to recent years  
(Fig. \ref{fig:catch_distn_a}). 
The 2021 A-season nominal catch rates
were lower than the 2020 peak (for the fleet in aggregate) (Fig. \ref{fig:fsh_cpue}). 
Beginning in 2017, due to  a regulatory
change, up to 45\% of the TAC could be taken in the A-season (previously only
40\% of the TAC could be taken). This conservation measure was made to allow
greater flexibility to avoid Chinook salmon in the B-season. To date, it
appears that the pollock fleet as a whole took advantage of  this added
flexibility (Fig. \ref{fig:prop_a_season}). However, this figure indicates that in 2021,
the proportion of catch in February dropped relative to recent patterns but was made up 
by the end of April. Pollock roe is an important product coming from the
winter fishery. The amount produced in the 2021 A-season was the lowest since 2016 and a 
considerable drop from the previous two years (Fig. \ref{fig:roe}).


The summer-fall fishing conditions for 2021 improved considerably over 2020 and was 
about average on nominal catch rates (Fig. \ref{fig:fsh_cpue}). The number of hours 
the fleet required to catch the same tonnage of pollock was also improved relative to 
2020.

Catches in the northwestern area dropped relative to the previous two years
(Fig. \ref{fig:catch_distn_b}). 
Also, the approach presented in 2019 to compute the fleet dispersion 
(the relative distance or spread of the fishery in space) indicated that 
in both seasons the fleet was less disperse than last year and 
was roughly similar to the recent lower concentration levels 
compared to other years since 2000 (Fig \ref{fig:fleet_dispersal}).

XX In addition to logistic issues related to ensuring crew and observer
safety due to the COVID19 pandemic, there were reports of unusually small 
pollock in the catch. Consequently, we investigated whether the amount
of small fish has occurred in the past. The NMFS observer collections, in
addition to containing value length and weight data, also include a large number
of observations for the observed tows that provide a direct mean somatic mass
for pollock within that tow. This is based on the sampled total weight (e.g.,
of a basket of pollock) divided by the enumerated number of fish in that sample.
Such records exist for each tow. Summing these by extrapolated weight of the
pollock catch within that tow, and binning by weight increments (here by 50
gram intervals), allows us to obtain some additional fine-scale information on
the size trends in the pollock fishery. The annual patterns of these data show
that overall, 2020 was different, particularly for the B-season 
(Fig. \ref{fig:fsh_wt_freq}). To look more closely at the B-season fishery, we
compiled these data by week over recent years and found that there were very
smaller fish predominated in the catch (Fig. \ref{fig:fsh_wt_freq_week}). 


The catch of EBS pollock has averaged 1.21 million t in the period since 1979. 
The lowest catches occurred in 2009 and 2010
when the limits were set to 0.81 million t due to stock declines (Table
\ref{tab:abc_tac}). The recent 5-year average (2017-2021) catch has been xxx1.365
million t. Pollock catches that are retained or discarded (based on NMFS
observer estimates) in the Eastern Bering Sea and Aleutian Islands for 
1991--`r thisyr` are shown in Table \ref{tab:catch_disc}. Since 1991, estimates of
discarded pollock have ranged from a high of 9.1\% of total pollock catch in
1992 to recent lows of around 0.6\%. These low values reflect the
implementation of the NMFS' Improved Retention /Improved Utilization
program. Prior to the implementation of the American Fisheries Act (AFA) in
1999, higher discards may have occurred under the “race for fish” and
pollock marketable sizes were caught incidentally. Since
implementation of the AFA, the vessel operators have more time to pursue
optimal sizes of pollock for market since the quota is allocated to vessels
(via cooperative arrangements). In addition, several vessels have made gear
modifications to avoid retention of smaller pollock. In all cases, the
magnitude of discards counts as part of the total catch for management (to
ensure the TAC is not exceeded) and within the assessment. Bycatch of other
non-target, target, and prohibited species is presented in the section titled
Ecosystem Considerations below. In that section it is noted that the bycatch
of pollock in other target fisheries is more than double the bycatch of other
target species (e.g., Pacific cod) in the pollock fishery.

## Management measures
The EBS pollock stock is managed by NMFS regulations that provide limits on
seasonal catch. The NMFS observer program data provide near real-time
statistics during the season and vessels operate within well-defined limits.
In most years, the TACs have been set well below the ABC value and catches have
stayed within these constraints (Table \ref{tab:abc_tac}). Allocations
of the TAC split first with 10\% to western Alaska communities as part of the
Community Development Quota (CDQ) program and the remainder between at-sea
processors and shore-based sectors. For a characterization of the CDQ program
see Haynie (2014).  Seung and Ianelli (2016) combined a fish population
dynamics model with an economic model to evaluate regional impacts.

Due to concerns that groundfish fisheries may impact the rebuilding of the
Steller sea lion population, a number of management measures have been
implemented over the years. Some measures were designed to reduce the
possibility of competitive interactions between fisheries and Steller sea
lions. For the pollock fisheries, seasonal fishery catch and pollock biomass
distributions (from surveys) indicated that the apparent disproportionately
high seasonal harvest rates within Steller sea lion critical habitat could
lead to reduced sea lion prey densities. Consequently, management measures
redistributed the fishery both temporally and spatially according to pollock
biomass distributions. This was intended to disperse fishing so that localized
harvest rates were more consistent with estimated annual exploitation rates. The
measures include establishing: 1) pollock fishery exclusion zones around sea
lion rookery or haulout sites; 2) phased-in reductions in the seasonal
proportions of TAC that can be taken from critical habitat; and 3) additional
seasonal TAC releases to disperse the fishery in time.

Prior to adoption of the above management measures, the pollock fishery
occurred in each of the three major NMFS management regions of the North
Pacific Ocean: the Aleutian Islands (1,001,780 km$^2$  inside the EEZ), the
Eastern Bering Sea (968,600 km$^2$), and the Gulf of Alaska (1,156,100 km$^2$). The
marine portion of Steller sea lion critical habitat in Alaska west of 150$^{\circ}$W
encompasses 386,770 km$^2$ of ocean surface, or 12\% of the fishery management
regions.

From 1995--1999 84,100 km$^2$, or 22\% of the Steller sea lion critical
habitat was closed to the pollock fishery. Most of this closure consisted of
the 10 and 20 nm radius all-trawl fishery exclusion zones around sea lion
rookeries (48,920 km$^2$, or 13\% of critical habitat). The remainder was
largely management area 518 (35,180 km$^2$, or 9\% of critical habitat) that
was closed pursuant to an international agreement to protect spawning stocks
of central Bering Sea pollock. In 1999, an additional 83,080 km$^2$ (21%) of
critical habitat in the Aleutian Islands was closed to pollock fishing along
with 43,170 km$^2$  (11%) around sea lion haulouts in the GOA and Eastern
Bering Sea. In 1998, over 22,000 t of pollock were caught in the Aleutian
Island region, with over 17,000 t taken within critical habitat region.
Between 1999 and 2004 a directed fishery for pollock was prohibited in this
region. Subsequently, 210,350 km$^2$  (54%) of critical habitat was closed to
the pollock fishery. In 2000 the remaining phased-in reductions in the
proportions of seasonal TAC that could be caught within the BSAI Steller sea
lion Conservation Area (SCA) were implemented.

On the EBS shelf, an estimate (based on observer at-sea data) of the
proportion of pollock caught in the SCA has averaged about 44% annually.
During the A-season, the average is also about 44%. Nonetheless, the
proportion of pollock caught within the SCA varies considerably, presumably
due to temperature regimes and the relative population age structure.  The
annual proportion of catch within the SCA varies and has ranged from an annual
low of 11% in 2010 to high of 60% in 1998--the 2019 annual value was 58% but
and quite high again in the A-season (68\%; Ianelli et al. 2020).
The higher values in recent years  were likely due to good fishing conditions close to
the main port. Note that the conversion of many catcher-vessels to shore-based 
biological sampling with at-sea operations monitored electronically, catch reporting to 
specific areas will be possible when the position information is fully operational
and offloads can be easily linked to haul records. Initial investigations on 
configuring these data for this purpose were promising and should be possible 
retroactively when the routines for the new database are developed further.

The AFA reduced the capacity of the catcher/processor fleet and permitted the
formation of cooperatives in each industry sector by the year 2000. Because of
some of its provisions, the AFA gave the industry the ability to respond
efficiently to changes mandated for sea lion conservation and salmon bycatch
measures. Without such a catch-share program, these additional measures would
likely have been less effective and less economical (Strong and Criddle 2014).

An additional strategy to minimize potential adverse effects on sea lion
populations is to disperse the fishery throughout more of the pollock range on
the Eastern Bering Sea shelf. While the distribution of fishing during the
A-season is limited due to ice and weather conditions, there appears to be
some dispersion to the northwest area (Fig. \ref{fig:catch_distn_a}).

The majority (about 56\%) of Chinook salmon caught as bycatch in the pollock
fishery originate from western Alaskan rivers. An Environmental Impact
Statement (EIS) was completed in 2009 in conjunction with the Council’s
recommended bycatch management approach. This EIS evaluated the relative
impacts of different bycatch management approaches as well as estimated the
impact of bycatch levels on adult equivalent salmon (AEQ) returning to river
systems (NMFS/NPFMC 2009). As a result, revised Chinook salmon bycatch
management measures went into effect in 2011 which imposed new prohibited
species catch (PSC) limits. These limits, when reached,  close the fishery by
sector and season (Amendment 91 to the BSAI Groundfish Fishery Management Plan
(FMP) resulting from the NPFMC’s 2009 action). Previously, all measures for
salmon bycatch imposed seasonal area closures when PSC levels reached the
limit (fishing could continue outside of the closed areas). The current
program imposes a dual cap system by fishing sector and season. A  goal of
this system was to maintain incentives to avoid bycatch at a broad range of
relative salmon abundance (and encounter rates). Participants are also
required to take part in an incentive  program agreement (IPA). These IPAs are
approved and reviewed annually by NMFS  to ensure individual vessel
accountability. The fishery has been operating under  rules to implement this
program since January 2011.

Further measures to reduce salmon bycatch in the pollock fishery were
developed and the Council took action on Amendment 110 to the BSAI Groundfish
FMP in April 2015. These additional measures were designed to add protection
for Chinook salmon by imposing more restrictive PSC limits in times of low
western Alaskan Chinook salmon abundance. This included provisions within the
IPAs that reduce fishing in months of higher bycatch encounters and mandate
the use of salmon excluders in trawl nets. These provisions were also included
to provide more flexible management measures for chum salmon bycatch within
the IPAs rather than through regulatory provisions implemented by Amendment 84
to the FMP. The new measure also included additional seasonal flexibility in
pollock fishing so that more pollock (proportionally) could be caught during
seasons when salmon bycatch rates were low.  Specifically, an additional 5% of
the pollock can be caught in the A-season (effectively changing the seasonal
allocation from 40% to 45% (as noted above in Fig. \ref{fig:prop_a_season}).
These measures are all part of Amendment 110 and a summary of this and other
key management measures is provided in Table \ref{tab:mgt}.

There are three time/area closures in regulation to minimize herring PSC
impacts: *Summer Herring Savings Area 1* an area south of 57$^\circ$N
latitude and between 162$^\circ$W
and 164$^\circ$W longitude from June 15 through July 1st.
*Summer Herring Savings Area 2* an area south of 56$^\circ$ 30' N latitude and
between
164$^\circ$W  and 167$^\circ$W longitude from July 1 through August 15.
*Winter Herring Savings Area* an area between 58$^\circ$  and 60$^\circ$N 
latitude and between 172$^\circ$W and 175$^\circ$W longitude from 
September 1st through  March 1st of the next fishing year.

The pollock fishery exceeded the herring PSC limit late in the 2020 A season 
which invoked two directed pollock fishing closures: the Summer Herring Savings 
Area 1 and the Winter Herring Savings Area (closed since September 1, 2020 through March 1, 2021).
Voluntary closures by the CV fleet for directed fishing for pollock.
2nd closure for trawl CVs for herring.
Additionally, voluntary closure areas were announced throughout
the B-season 2020 and intended to minimize herring bycatch in areas where
herring occurred.

## Economic conditions as of 2020

Alaska pollock is the dominant species in terms of catch in the Bering Sea \&
Aleutian Island (BSAI) region. In 2020 pollock accounted for 72\% of the
BSAI's FMP groundfish harvest and 93\% of the total pollock harvest in Alaska.
Retained catch of pollock decreased 2.9\% to 1.37 million t in 2020 (Table \ref{tab:bsaiplck_exv}).
The decrease in 2020 catch was despite an increase in the TAC as poor fishing conditions 
resulted in only 95\% of the TAC being harvested.
BSAI pollock first-wholesale value was \$1.37 billion 2020, which was a 12\% decrease
from 2019 and above the 2011--2015 average of \$1.31 billion (Table \ref{tab:bsaiplck_wsl}). 
The decrease in
2020 revenues was largely driven by the decrease in catch and corresponding production
as the average first-wholesale price was stable (Table \ref{tab:bsaiplck_wsl}). The
increases in the average first-wholesale price of pollock products in 2016 and 2017
were largely due to increases the price of surimi products while the price increase
in 2018 was largely due to an increase in the price of fillets. Price increases in 2019 
were the combined effect of price increases in both fillets and surimi. In 2020, price 
increases in fishmeal and minced fish offset decreases in the H\&G, roe and surimi prices
while fillet prices stable. The primary revenue impact of COVID-19 pandemic was increased 
demand for retail products which put upward pressure on retail focused products like 
single-frozen fillets, minced, and surimi. However, smaller average size of fish in
catch limited the quantity and grades of product forms which generally put downward 
pressure on prices.

Pollock is targeted exclusively with pelagic trawl gear. The catch of pollock
in the BSAI was rationalized with the passage of the
AFA in 1998,\footnote{The AFA was implemented in 1999 for
catcher/processors, and in 2000 for catcher vessel and motherships.} which,
among other things, established a proportional allocation of the total
allowable catch (TAC) among vessels in sectors which were allowed to form into
cooperatives.\footnote{The BSAI pollock TAC is divided between Community
Development Program (10\% off the top), with the remaining amount split among shore-based
catcher vessels (50\%), at-sea catcher/processors (40\%) and motherships (10\%).}

Prior to 2008 pollock catches were high at approximately 1.4 million t in the
BSAI for an extended period (Table \ref{tab:bsaiplck_exv}). The U.S. accounted
for over 50\% of the global pollock catch.
Between 2008--2010 conservation reductions in the pollock total allowable catch
(TAC) trimmed catches to an average 867 kt. The supply reduction
resulted in price increases for most pollock products, which mitigated the
short-term revenue loss (Table \ref{tab:bsaiplck_glbl}). Over this same
period, the pollock catch in Russia increased from an average of 1 million t
in 2005--2007 to 1.4 million t in 2008--2010 and Russia's share of global catch
increased to over 50\% and the U.S. share decreased to 35\%. Since 2011 the U.S. 
has accounted for approximately 44\% of the global pollock catch the majority of
which comes from the BSAI (Table \ref{tab:bsaiplck_glbl}).

Russia has histoically lacked the
primary processing capacity of the U.S., with much of their catch being exported to
China where it is re-processed as twice-frozen fillets. In recent years Russia has pursued
upgrading its processing capacity of fillets, minced, roe, and surimi which could compete more 
directly with primary processed products made by the U.S..
Around the mid- to late-
2000s, buyers in Europe, an important segment of the fillet market, started to
source fish products with the MSC sustainability certification, and
retailers in the U.S. later began to follow suit. Asian markets, an important
export destination for a number of pollock products, have shown less interest
in requiring MSC certification. The U.S. was the only producer of MSC
certified pollock until 2013 when roughly 50\% of the Russian catch became MSC
certified.\footnote{Alaska caught pollock in
the BSAI became certified by the Marine Stewardship Council (MSC) in 2005, an
NGO based third-party sustainability certification, which some buyers seek.}
Since 2010 the U.S. pollock stock rebounded with catches in the
BSAI ranging from 1.2--1.3 million t and Russia's catch has stabilized at 1.5
to 1.6 million t. The majority of pollock is exported; consequently exchange
rates can have a significant impact on market dynamics, particularly the
Dollar-Yen and Dollar-Euro.\footnote{Aggregate exports in Table \ref{tab:bsaiplck_glbl}
may not fully account for all pollock exports as products such as meal,
minced fish and other ancillary product may be coded as generic fish type for export purposes.}
In 2015 the official U.S. market name changed from "Alaska pollock" to
"pollock" enabling U.S. retailers to differentiate between pollock caught in
Alaska and Russia. Additionally, pollock more broadly competes with other whitefish that,
to varying degrees, can serve as substitutes depending on the product. The pollock industry
has avoided U.S. tariffs that would have a significant negative impact on them in the
U.S.-China trade war. However, Chinese tariffs on U.S. products could
inhibit growth in that market.

This market environment accounts for some of the major trends in prices and
production across product types. Fillet prices peaked in 2008--2010 but
declined afterwards because of the greater supply from U.S. and Russia. The
2013 MSC certification of Russian-caught pollock enabled access to segments of
European and U.S. fillet markets, which has put continued downward pressure on
prices. Pollock roe prices and production have declined steadily over the last
decade as international demand has waned with changing consumer preferences in
Asia. Additionally, the supply of pollock roe from Russia has increased with
catch. The net effect has been not only a reduction in the supply of roe from
the U.S. industry, but also a significant reduction in roe prices which are
roughly half pre-2008 levels. Prior to 2008, roe comprised 23\% of the U.S.
wholesale value share, and since 2011 it has been roughly 10\% (Table \ref{tab:bsaiplck_wsl}). With the U.S.
supply reduction in 2008--2010, surimi production from pollock came under
increased pressure as U.S. pollock prices rose and markets sought cheaper
sources of raw materials (see Guenneugues and Ianelli 2013 for a global review
of surimi resources and market). This contributed to a growth in surimi from
warm-water fish of southeast Asia. Surimi prices spiked in 2008--2010 and have
since tapered off as production from warm-water species increased (as has
pollock). Surimi is consumed globally, but Asian markets dominate
the demand for surimi and demand has remained strong.

The catch of pollock can be broadly divided between the shore-based sector
where catcher vessels make deliveries to inshore processors, and the at-sea
sector where catch is processed at-sea by catcher/processors and motherships
before going directly to the wholesale markets. The retained catch of the
shore-based sector decreased 1\% to 725 kt. The value of these
deliveries (shore-based ex-vessel value) totaled \$233.7 million in 2020,
which was down 10\% from the ex-vessel value in 2019 driven mostly by a 7\%
decrease in the ex-vessel price which was just below the 2011-2015 average
(Table \ref{tab:bsaiplck_exv}). The first-wholesale value of pollock products was
\$814 million for the at-sea sector and \$552 million for the shore-based
sector (Table \ref{tab:bsaiplck_wsl}). The
average price of pollock products in 2020 increased 2\% for the at-sea sector to
$1.41 and
decreased 4\% for the shore-based sector to $1.08. Surimi prices decreased 8\%, 
fillet prices increased 3\%, and roe prices decreased 7\% in 2020. Minced prices 
increased 11\% and minced production rose 38\% as demand for retail products increased
as a result of COVID-19. Fishmeal prices rose 43\% with a reduced Peruvian fishmeal 
supply because of a temporary fishery closure early in the year.

The portfolios of products shore-based and at-sea processors produce are
similar. In both sectors the primary products processed from pollock are
fillets, surimi and roe, with each accounting for approximately 40\%, 40\%,
and 10\% of first-wholesale value (Table \ref{tab:bsaiplck_wsl}). The price of
products produced at-sea tend to be higher than comparable products produced
by the shore-based because of the shorter time span between catch, processing and
freezing. Over the past 5 years the price of fillets produced at-sea tend to be about
7\% higher, surimi prices tend to be about 25\% higher and the price of roe
about 50\% higher. Average prices for fillets produced at-sea also tend to be
higher because they produce proportionally more higher-priced fillet types
(like deep-skin fillets). The at-sea price first wholesale premium averaged
roughly \$0.20 per pound between 2011--2015 and has increased to an average of
\$0.28 per pound between 2016--2020.\footnote{The at-sea price
premium is the difference between the average price of first-wholesale
products at-sea and the average price of first-wholesale products shore-
based.}

### Pollock fillets

A variety of different fillets are produced from pollock, with pin-bone-out
(PBO) and deep-skin fillets typically accounting for approximately 70\% and
30\% of production in the BSAI, respectively. Deep-skin fillet's share of fillet
production was 34\% in 2020. Total fillet production decreased 20\%
to 149 kt in 2020, and was below the the 2011--2015 average (Table
\ref{tab:bsaiplck_wsl}). The average price of fillet products in the BSAI
increased 3\% to \$1.56 per pound and is below the inflation adjusted average
price of fillets in 2011--2015 of \$1.63 per pound (2020 dollars). Media
reports indicate that for single-frozen fillets increased retail demand stemming 
from COVID-19 supported strong prices, however, low double-frozen fillets prices 
(which have a strong foodservice component) put downward pressure on 
single-frozen prices. The decrease in fillet volumes was related to smaller fish 
size in the 2020 catch which are less suited to fillet production and better suited
for minced which saw significant increases in both volume and value.

Pollock fillets sourced from Russia
are a competitor to Alaska sourced pollock fillets.
Fillets were a relatively small portion of Russian primary production
however, they are increasing their fillet production capacity. Much of the
Russian catch goes to China for secondary processing into fillets so
this would do little to increase the overall volume, however, increased
primary fillet processing in Russia could increase competition with U.S.
produced single-frozen fillet products. Using data through 2017 approximately 30\% of the fillets
produced in Alaska are estimated to remain in the domestic market, which
accounts for roughly 45\% of domestic pollock fillet consumption (AFSC
2020).\footnote{Additionally, roughly 10\% of the at-sea BSAI production is
processed as H\&G which is mostly exported, primarily to China, where is
reprocessed as fillets and some share of which returns to the U.S.. China also
processes H\&G from Russia into fillets which are also imported into the
domestic market. Current data collection does not allow us to estimate the
share of U.S. returning imports.} The U.S. industry has tried to maintain value
over the years by
increasing domestic marketing for fillet based product and creating product
types that are better suited to the American palette, in addition to increased
utilization of by-products. 

### Surimi seafood

Surimi production in 2020 was 171.7 kt, which was down 11\%
and was above the 2011--2015 average. Prices have generally increased since 2013
and although they fell 8\% in 2020 to \$1.26 they remain strong (Table
\ref{tab:bsaiplck_wsl}). Surimi is primarily a retail product, and demand in 2020
was strong with the increased focus on retail resulting from COVID-19 pandemic. 
Furthermore, the supply tropical species used to produce surimi has been tight. The
smaller-sized fish caught by the U.S. in 2020 is better suited to production of 
low- to mid-grade surimi which puts downward pressure on surimi prices. Demand for 
high-grade surimi is high and supplies were tight.
Because surimi and fillets are both made from pollock
meat, activity in the fillet market can influence the decision of processors
to produce surimi as smaller average size of fish can incentivize surimi
production, particularly if it yields a higher value than fillets. 

### Pollock roe

Roe is a high priced product that is the focus of the A season catch destined
primarily for Asian markets. Roe production in the BSAI averaged 27 kt in 
2005--2007 and tapered off in the
late--2000s and since has generally fluctuated at under or near 20 kt annually.
Roe production decreased to 24.7 kt in 2020 and was above the 2011-2015 average
(Fig. \ref{fig:roe}). Prices peaked in the mid-2000s and have
followed a decreasing trend over the last decade which continued until 2015,
after which prices increased to \$2.89 per pound in 2018.
The Yen to U.S. Dollar exchange rate can influence prices and strengthed against 
the Yen in 2020. The average roe price in the BSAI was down 7\% in
2020 to \$2.01 per pound, the lowest observed. Value fell 17\% with the decrease in
production to \$109.1 million (Table \ref{tab:bsaiplck_wsl}).

### Fish oil

Using oil production per 100 tons as a basic index (tons of oil per ton
retained catch) shows increases for the at-sea sector. In 2005--2007 it was
0.3\% and starting in 2008 it increased and leveled off after 2010 with over
1.5\% of the catch being converted to fish oil (Table \ref{tab:bsaiplck_oil}).
This represents about a 5-fold increase in recorded oil production during this
period. Oil production from the shore-based fleet was somewhat higher than the
at-sea processors prior to 2008 but has been relatively stable. Oil production
estimates from the shore-based fleet may be
biased low because some production occurs at secondary processors (fishmeal
plants) in Alaska. The increased production of oil beginning in 2008 can be
attributed to the steady trend to add more value per ton of fish landed.
The oil production index decrased 27\% in 2020 and was at levels not seen 
since before 2012.

# Data

The following lists the data used in this assessment: 

\begin{table}[ht]
\centering
\label{tab:dataextent}
\begin{tabular}{p{1.5in}p{1.8in}p{2.8in}}
\hline
 Source & Type & Years \\
\hline
 Fishery & Catch biomass & 1964--`r thisyr` \\
 Fishery & Catch age composition & 1964--`r lastyr` \\
 Fishery & Japanese trawl CPUE & 1965--1976 \\
 EBS bottom trawl & Area-swept biomass and age-specific proportions & 1982--2019, `r thisyr-1 ` \\ 
 Acoustic trawl survey & Biomass index and age-specific
 proportions & 1994, 1996, 1997, 1999, 2000, 2002, 2004, 2006--2010, 2012, 2014, 2016, 2018, 2020 \\
 Acoustic vessels of opportunity (AVO) & Biomass index & 2006--2019, `r thisyr` \\
\hline
\end{tabular}
\end{table}
_Note the 2020 acoustic survey data based on unmanned surface vessel (USV) transects_ 

## Fishery

### Catch

The catch-at-age composition was estimated using the methods described by
Kimura (1989) and modified by Dorn (1992). Length-stratified age data are used
to construct age-length keys for each stratum and sex. These keys are then
applied to randomly sampled catch length frequency data. The stratum-specific
age composition estimates are then weighted by the catch within each stratum
to arrive at an overall age composition for each year. Data were collected
through shore-side sampling and at-sea observers. The three strata for the EBS
were:  i) January–June (all areas, but mainly east of 170$^\circ$W); ii) INPFC area
51 (east of 170$^\circ$W) from July–December; and iii) INPFC area 52 (west of 170$^\circ$W)
from July–December. This method was used to derive the age compositions from
1991--`r lastyr` (the period for which all the necessary information is readily
available). Prior to 1991, we used the same catch-at-age composition estimates
as presented in Wespestad et al. (1996).

The catch-at-age estimation method uses a two-stage bootstrap re-sampling of
the data. Observed tows were first selected with replacement, followed by re-
sampling actual lengths and age specimens given that set of tows. This method
allows an objective way to specify the effective sample size for fitting
fishery age composition data within the assessment model. In addition,
estimates of stratum-specific fishery mean weights-at-age (and variances) are
provided which are useful for evaluating general patterns in growth and growth
variability. For example, Ianelli et al. (2007) showed that seasonal aspects
of pollock condition factor could affect estimates of mean weight-at-age. They
showed that within a year, the condition factor for pollock varies by more
than 15%, with the heaviest pollock caught late in the year from October-
December (although most fishing occurs during other times of the year) and the
thinnest fish at length tending to occur in late winter. They also showed that
spatial patterns in the fishery affect mean weights, particularly when the
fishery is shifted more towards the northwest where pollock tend to be smaller
at age. In 2011 the winter fishery catch consisted primarily of age 5 pollock
(the 2006 year class) and later in that year age 3 pollock (the 2008 year
class) were present. In 2012--2016 the 2008 year class was prominent in the
catches with 2015 showing the first signs of the 2012 year-class as three
year-olds in the catch (Fig. \ref{fig:catage}; Table \ref{tab:fsh_age}). However,
by 2017 the 2013 year-class began to be also evident, and surpassed the 2012 
year-class in dominance and continued through to 2020. In 2020, an unusual 
presents of age-2 pollock appeared in the catch, along with some from the 
2014 year-class while the 2012 year-class was a small part of the catch 
(Fig. \ref{fig:catage}). The unusual pattern of switching adjacent year-classes
was examined more closely to see if there was a pattern of spatial differences.
Plotting the locales where the aged fish arose shows some separation with the 2013
year-class occuring further north (Fig. \ref{fig:fsh_cohort_locales}). This could
be due to a number of factors including the relative concentrations of the 
original spawning fish and the relatively warm conditions which may have reduced
the potential overlap and vulnerability to cannibalism.

The sampling effort for age determinations, weight-length measurements, and length
frequencies is shown in Tables \ref{tab:fsh_meas}, \ref{tab:lw_meas}, and
\ref{tab:fsh_n}. Sampling for pollock lengths and ages by area has been shown
to be relatively proportional to catches (e.g., Fig. 1.8 in Ianelli et al.
2004).  The precision of total pollock catch biomass is considered high with
estimated  CVs to be on the order of 1\% (Miller 2005).

Scientific research catches are reported to fulfill requirements of the
Magnuson-Stevens Fisheries Conservation and Management Act. The annual
estimated research catches (1963--2018) from NMFS surveys in the Bering Sea
and Aleutian Islands Region are given in (Table \ref{tab:res_catch}). Since
these values represent extremely small fractions of the total removals
(about 0.02%) they are ignored for assessment purposes.

## Surveys

### Bottom trawl survey (BTS)

Trawl surveys have been conducted annually by the AFSC to assess the abundance
of crab and groundfish in the Eastern Bering Sea since 1979 and since 1982
using standardized gear and methods. For pollock, this survey has been
instrumental in providing an abundance index and information on the population
age structure. This survey is complemented by the acoustic trawl (AT) surveys
that sample mid-water components of the pollock stock. Between 1991 and 2021
the BTS biomass estimates ranged from 2.28 to 8.39 million t 
(Table \ref{tab:bts_biom}; Fig. \ref{fig:bts_biom}). In the mid-1980s and early
1990s several years resulted in above-average biomass estimates. The stock
appeared to be at lower levels during 1996--1999 then increased moderately
until about 2003 and since then has averaged just over 4 million t (from the 
standard EBS region using design-based estimators). These
surveys also provide consistent measurements of environmental conditions, such
as the sea surface and bottom temperatures. Large-scale zoogeographic shifts in
the EBS shelf documented during a warming trend in the early 2000s were
attributed to temperature changes (e.g., Mueter and Litzow 2008). However,
after the period of relatively warm conditions ended in 2005, the next eight
years were mainly below average, indicating that the zoogeographic responses
may be less temperature-dependent than they initially appeared (Kotwicki and
Lauth 2013). Bottom temperatures increased in 2011 to about average from the
low value in 2010 but declined again in 2012--2013. However, in the period
2014--2016, bottom temperatures increased and reached a new high in 2016. In
2018 bottom temperatures were nearly as warm (after 2017 was
slightly above average) but was highly unusual due to the complete lack of 
"cold pool" (i.e., a defined area where water near bottom was less 
than zero degrees. In 2019, the mean bottom temperature was the warmest during
the period the survey has occurred (since 1982;  Fig. \ref{fig:bts_temp}).  In
2020 the survey was canceled and detailed data were
unavailable (although the 2020 Ecosystem report (Siddon 2020) contains model
estimates of temperature distributions for the region and indicates that the bottom temperatures 
and cold pool extent were about average). In 2021, the temperatures on bottom were above average
again with a relatively constricted cold pool extent.

The AFSC has expanded the area covered by the bottom trawl survey over time.
In 1987 the "standard survey area" comprising 6 main strata was increased 
farther to the northwest and covered in all subsequent years. These two
northern strata have varied in estimated pollock abundance.
In 2021 about 9\% of the pollock biomass was found in these strata compared
to a long term average of 5\% (Table \ref{tab:bts_biom}). 
Importantly, this region is contiguous with the Russian
border and the NBS region, and measures to increase consideration of those regions
relative to the exploited pollock stock continues (e.g., O'leary et al.
Submitted).

As noted last year, the 2019 bottom-trawl survey biomass estimate (design-based,
area swept) was 5.48 million t, above the average for this survey (4.7 million t). 
This was a substantial increase over the 3.11 million t estimated from
the 2018 estimates. Both years were unusual in
that there was a near-complete lack of cold water on the bottom 
throughout the survey area (Fig. \ref{fig:bts_temp_cpue}). 
Pollock appeared to be distributed more broadly over the shelf
 in 2019, different than in 2017 and 2018 where fish were more concentrated
  (Fig. \ref{fig:bts_3d}).  

The BTS abundance-at-age estimates show variability in year-class strengths
with substantial consistency over time (Fig. \ref{fig:bts_age}). Pollock above
40 cm in length generally appear to be fully selected and in some years many
1-year olds occur on or near the bottom (with modal lengths around 10--19 cm).
Generally speaking, age 2 or 3 pollock (lengths around 20--29 cm and 30--39 cm, respectively) are
relatively rare in this survey because they tend to be more pelagic as
juveniles. In 2021, the relative abundance of these size ranges was more apparent
and this was unusual compared to the other years (Fig. \ref{fig:bts_lenfreq}).

Observed fluctuations in survey estimates may be attributed to a
variety of sources including unaccounted-for variability in natural mortality,
survey catchability, and migrations. As an example, some strong year classes
appear in the surveys over several ages (e.g., the 1989 year class) while
others appear only at older ages (e.g., the 1992 and 2008 year class).
Sometimes initially strong year classes appear to wane in successive
assessments (e.g., the 1996 year class estimate (at age 1) dropped from 43
billion fish in 2003 to 32 billion in 2007 (Ianelli et al. 2007).
Retrospective analyses (e.g., Parma 1993) have also highlighted these
patterns, as presented in Ianelli et al. (2006, 2011). Kotwicki et al. (2013)
also found that the catchability of either the BTS or AT survey for pollock is
variable in space and time because it depends on environmental variables, and
is density-dependent in the case of the BTS survey.

The 2019 survey age compositions were developed from age-structures collected
during the survey (June-July) and processed at the AFSC labs within a few
weeks after the survey was completed. The level of sampling for lengths and
ages in the BTS is shown in (Table \ref{tab:bts_n}). The estimated numbers-at-
age from the BTS for strata (1--9 except for 1982--84 and 1986, when only strata
1--6 were surveyed) are presented in Table \ref{tab:bts_age} 
(based on the method in Kotwicki et al. 2014). Mean body mass at ages from the survey are
shown in (Table \ref{tab:wt_bts}) and the different alternative time series
of BTS survey indices is shown in Table \ref{tab:bts_abund}.

The NBS survey area was sampled in 2010, 2017, 2018 (limited
to 49 stations), and in 2019. Given that the pollock abundance
was quite high in 2017 and 2018, a method for incorporating this information
as part of the standard survey was desired. One approach for constructing a
full time series  that included the NBS area is to use observed spatial and
temporal correlations. We used the vector-autoregressive spatial temporal
(VAST) model of Thorson (2018b) together with the density- dependent corrected
CPUE values from each station (including stations where pollock were absent;
Table \ref{tab:bts_abund}). Please refer to the appendix for further details
on the implementation. The appendix also shows results that indicate the VAST
model diagnostics are reasonable and provide consistent interpretations
relative to the observations. Notably, results indicate increased uncertainty
in years and areas when stations were missing.  As noted in past
assessments, application of this index
within the stock assessment model required accounting for the temporal
covariation. 

### Acoustic trawl (AT) surveys

Acoustic trawl (AT) surveys The AT surveys are typically conducted every other year and are designed
to estimate the off- bottom component of the pollock stock (compared to the BTS which are conducted
annually and provide an abundance index of the near-bottom pollock). The number of trawl hauls,
lengths, and ages sampled from the AT survey are presented in  (Table \ref{tab:bts_abund}).

Estimated pollock biomass (to 0.5m from bottom) for the EBS shelf was above 4 million tons in the
early years of the time series (prior to 1998  Table \ref{tab:bts_abund} ).   Biomass dipped below 2
million t in 1991. Since 1994, the years for which AT survey estimates are  available to within 0.5
m of bottom, the biomass increased and remained between about 3 and 4.5 million t for a decade
(1994–2004). The early 2000s (a relatively ‘warm’ period) were characterized by low  pollock
recruitment, which was subsequently reflected in lower pollock biomass estimates between 2006 and
2012 (a ‘cold’ period; Honkalehto and McCarthy 2015). In 2014 and 2016 (another ‘warm’ period) with
the growth of the strong 2012 year class, AT biomass estimates increased to over
4 million t, exceeding levels observed in 1994-2004  (Table \ref{tab:bts_abund}).

Relative estimation errors for the total biomass were derived from a one-dimensional (1D)
geostatistical method, which accounts for observed spatial structure for sampling along transects 
(Table 21; Petitgas 1993, Walline 2007, Williamson and Traynor 1996).  As in previous assessments,
the other sources of error (e.g., target strength, trawl selectivity) were accounted for by
inflating the annual error estimates to have an overall average CV of 20% for
application within the assessment model.  The age composition data from the ATS sampling are provided in  
Table \ref{tab:ats_age}).

<!--
#### Uncrewed surface vehicle (USV) deployment and data processing

NOAA’s fisheries research vessel
was unable to perform the planned 2020 acoustic-trawl survey due to the COVID-19 pandemic. 
Instead, three chartered  Saildrone$^{(TM)}$ uncrewed surface vehicles (USVs) were
deployed from Alameda, CA, to the Bering Sea to perform this task. 
AFSC scientists acted quickly with support from NOAA’s office
of science and technology in the late spring to organize this as an option given the potential for
surveys to be canceled or curtailed. 
This contingency plan was possible due to AFSC’s previous
experience working closely as part of a private-public partnership between Saildrone, Simrad, and
NOAA Research’s Pacific Marine Environmental Laboratory (PMEL). 
Saildrone has collaborated with the
AFSC and PMEL on several missions in the Arctic since 2016 to develop the vehicle’s capabilities and
refine the sensors (Meinig et al., 2019).  
The USVs were equipped with Simrad EK80 mini split-beam
echo sounders equivalent to those used on NOAA surveys (De Robertis et al., 2019).  
In addition, they are equipped with a suite of instruments to collect oceanographic and meteorological data above
and below the sea surface including air and sea temperatures, wind speed and direction, relative
humidity, barometric pressure, photosynthetically active radiation, salinity, dissolved oxygen,
chlorophyll fluorescence, and wave height and period (Mordy et al., 2017). 
Data summaries are transmitted to shore via a satellite link, and the vehicles are controlled over this link.  
Missions include studying the impacts of climate variability and other environmental aspects on northern fur
seals and other marine mammal populations, measuring carbon dioxide and the abundance of Arctic cod,
collecting observations for sea ice prediction and satellite algorithm development, and tracking
Alaska red king crab (e.g. Mordy et al., 2017, De Robertis et al. 2019, Levine et al., in press).
Comparisons of backscatter recorded from saildrone USVs and ‘follow the leader’ vessel comparisons
conducted during the 2016 EBS survey have confirmed that the USVs and the NOAA ship Oscar Dyson
produce equivalent measurements of pollock backscatter under survey conditions (De Robertis et al.,
2019).

The ship-based AT surveys use trawls to sample fish aggregations observed
acoustically. One drawback of using the USVs is the inability to confirm the
species, size, and biological characteristics of the acoustic backscatter. The
lack of biological samples affects the ability to convert the areal measures of
acoustic backscatter (sA, m2 nmi-2) into pollock biomass. The conversion depends
on the species composition and size distribution of the backscattering
organisms. Also, biological samples help determine the age composition of the
pollock that are within the backscatter. Fortunately, midwater fish in the
survey area are predominately pollock (Fig. \ref{fig:at_pollock_in_sa}).  This
simplifies the interpretation of acoustic measurements since fish aggregations
are most likely to be pollock (e.g. as is assumed in the AVO backscatter index
derived from the bottom trawl charter vessels (Honkalehto et al., 2011).
Nonetheless, retrospective analysis indicates that there is a strong
relationship between total backscatter and biomass estimates from the research
ships (Fig. \ref{fig:at_sa_biom}).  As a result, linear regressions of these
relationships (Fig. \ref{fig:at_sa_biom_regress}) were used to convert the
acoustic backscatter to biomass for the USV data collected in 2020.  As in
previous surveys, the midwater component (>3m above bottom), and the demersal
component ( 0.5 to 3m above bottom) were converted to biomass using separate
relationships and then combined as demersal community composition is more
diverse than in midwater (Lauffenburger et al., 2017).  A sensitivity analysis
in which the biomass in each year was predicted based on the trawl samples in
other years rather than the trawl observations in that year suggests that this
conversion does not alter the primary trends in the time series (Fig.
\ref{fig:at_usv_biom}).

Another component of uncertainty for the USV data was the fact that due to time constraints, the
transect spacing to cover the area of the EBS had to be doubled (this survey design was a
contingency plan in case the Dyson was delayed but available for the survey). 
To evaluate the impact of this, we compared past surveys and computed biomass and uncertainty 
estimates as if the even number (20-mile transects) were dropped or alternatively the odd numbered transects. 
Results from this showed that the estimates were consistent with the “full” survey (at 20-mile transects) but
that the uncertainty increased (Fig. \ref{fig:at_transect_spacing}).
Similar comparisons using the 1-D geostatistical technique are ongoing and have produced similar 
initial results (i.e. the coefficient of variation
(CV) increases approximately two fold for 40 nmi spacing compared to 20 nmi spacing). 
The uncertainty of the survey was characterized by increasing the observed 1-D CV based on the
prediction intervals based on a Monte-Carlo which accounts for the additional variance introduced by
the unit conversion from backscatter to biomass. 
  
In 2020 the acoustic backscatter index increased by 45.2\% relative to 
the last survey in 2018  (Fig. \ref{fig:at_sa_biom}).
Converting to biomass, the estimate increased by 44.5% to 3.6 million t 
(the 2018 estimate was 2.5 million t; Fig. \ref{fig:at_biom}).
The CV based on the 1-D geostatistical estimate for backscatter
measurements 2020 was 6.9%, which increased to 9.7% when the additional uncertainty of the
backscatter to biomass conversion was added (Fig. \ref{fig:at_biom}). 
This CV is 2.6 times the average CV of the 1994-2020 time series  (3.8%, see (Fig. \ref{fig:at_biom}).
The backscatter data show that the density of pollock was highest in the northwest portion of the survey area
(Fig. \ref{fig:at_sa_map}). The proportion of backscatter in the lower three meters was consistent with observations in previous years 
(Fig. \ref{fig:at_sa_prop}). which suggests that the difference in beamwidth between the USV and the research vessels used for previous
surveys did not introduce a major bias.  Finally, a VAST-spatio-temporal model based on backscatter
data which expanded the survey grid to the area covered by the BTS survey (see appendix for details)
was used to enabled visualization of past surveys, and to computing an alternate index extrapolated
over a larger survey area than that occupied by the survey  (Fig. \ref{fig:at_sa_density}).
The VAST and design based survey estimates were considered as inputs to the assessment model.
-->

## Other time series used in the assessment

### Japanese fishery CPUE index
An available time series relating the
abundance of pollock during the period 1965--1976 was included. This series is
based on Japanese  fishery catch rates which used the same size class of trawl
vessels   as presented in  Low and Ikeda (1980). A coefficient of variation of
20\% was applied.

### Biomass index from Acoustic-Vessels-of-Opportunity (AVO)

Acoustic backscatter data (Simrad ES60, 38 kHz) were collected aboard two
fishing vessels chartered for the AFSC summer 2021 bottom trawl surveys (F/V
Alaska Knight, F/V Vesteraalen).  These Acoustic Vessels of Opportunity (AVO)
data were processed according to Honkalehto et al. (2011) to provide an index of
age-1+ midwater pollock abundance in each year.  

The 2021 AVO index of midwater pollock abundance on the eastern Bering Sea shelf
increased by 38% from 2019 and is the 2nd highest value on record (1.8% less
than the highest value recorded in 2015) (Table \ref{tab:avo}; note the AVO data
were unavailable in 2020 since the BTS was canceled).  Spatially, the total
pollock backscatter observed east of the Pribilof Islands during the summers of
2010-2012 ranged from 4-9%.  Since 2013 the backscatter from this area ranged
between 15% and 25%. (Fig. \ref{fig:data_avomap}).  



# Analytic approach

## General model structure

A statistical age-structured assessment model conceptually outlined in
Fournier and Archibald (1982) and like Methot’s (1990) stock synthesis model
was applied over the period 1964--`r thisyr`. A technical description is 
presented in the Model Details section attached. The analysis was first 
introduced in the 1996 SAFE report and compared to the cohort analyses 
that had been used previously and was later documented in Ianelli and Fournier (1998). 
The model was written in "ADMB"--a library for non-linear estimation and statistical
applications (Fournier et al. 2012). The data updated from last year’s
analyses include:

  - The `r thisyr-1` fishery age composition data were added 

  - The catch biomass estimates were updated through to the current year    

  - The USV backscatter data collected in 2020 was converted to biomass and
   applied as an extension of the ATS time series

A simplified version of the assessment (with mainly the same data and
likelihood-fitting method) is included as a supplemental multi-species
assessment model. As presented since 2016, it allows for trophic interactions
among key prey and predator species and for pollock, and it can be used to
evaluate age and time-varying natural mortality estimates in addition to
alternative catch scenarios and management targets (see this volume:
[EBS multi-species model](https://archive.fisheries.noaa.gov/afsc/refm/stocks/plan_team/2020/EBSmultispp.pdf)).

## Description of alternative models
In the 2019 assessment, the spatio-temporal model fit to
BTS CPUE data _including stations from the NBS_ was expanded using
the VAST methods detailed in Thorson (2018). This data treatment was
included as a model alternative and adopted for ABC/OFL specifications
by the SSC. This application also included a spatio-temporal treatment of the
age composition data which showed minor differences 
compared to the standard design-based expansion of ages. Using the SSC
convention for model numbering they selected "Model 20.0" which had a new data type. 
Model 20.0 (also referred to as the "base" model---and is identical to the 2020 model 
selected by the SSC but includes updated fishery catch-at-age and catch biomass data).
We examined the influence of additional data new to this assessment, but restrict expansion to
alternative "models" this year (but do examine alternative Tier scenarios). We note that 
tests of the pollock data for this assessment have been developed using models presented in Li et al. (2021)
and others but the features (e.g., using an informed fixed-effects model for projecting weight-at-age and
allowing a covariance matrix for index time series) has restricted adopting a more commonly
used assessment framework. 

### Tier 1 considerations
In the 2020 assessment we examined the factors
affecting Tier 1 classifications including the required "reliability" of the estimated pdf of $F_{MSY}$, 
i.e., the influence of assumptions related to the uncertainties on the stock 
recruitment relationship, body mass-at-age, maturation, and fishery selectivity.
For a number of years the Tier 1 ABC and OFL specifications for EBS pollock have
been very high, in excess of the 2 million t OY for combined groundfish stocks
managed within this FMP area. This has been because the spawning stock estimates
have been well above target and mean levels. To add precaution to these
estimates, ABC recommendations have been below the maximum permissible under
Tier 1 but the rationale for such an adjustment could be improved.
As such, the SSC requested an examination of the issues related to
classifying this stock in Tier 1 versus Tier 3. The FMP (under amendment
56) guides this classification. It notes that a reliable estimate of
$F_{MSY}$ and its uncertainty (as expressed through a probability
distribution or PDF) is required. Since these values depend primarily on
the stock-recruitment relationship (SRR), the following sensitivities were pursued
relative to the status quo (Model 20.0) configuration:

  a) As status quo but ignore influence of the 1978 year class on SRR 

  b) As in sensitivity a) but with a less informative prior on steepness

  c) As in status quo but the SRR conditioned such that $F_{MSY}=F_{35\%}$

  d) As in status quo but the SRR conditioned such that $F_{MSY}=F_{45\%}$


The first option is intended to reflect that the high value observed of the 1978
year-class occurred under an estimated low level of spawning biomass (designated Model 20.0a). The
rationale for excluding this influential value was be that the stock structure
and environmental conditions may differ now indicating non-stationarity in the relationship. Results showed that it mattered but was
relatively minor and seemed unlikely to disqualify the estimates required for Tier 1.
Sensitivity test b) was intended to illustrate the role of the prior mean and variance on the steepness estimate.
Finally sensitivities c) and d) were considered as how the SRR may translate an
implicit assumption under Tier 3 since $F_{35\%}$ is a proxy for $F_{MSY}$ and
$F_{45\%}$ is closer to the recent mean SPR rate. 

### Input sample size
Sample sizes for age-composition data were re-evaluated in 2016 against
the trade-off with flexibility in time and age varying selectivity. This 
resulted in tuning the recent era (1991-present year) to average sample 
sizes of 350 for the fishery and then using estimated values for the 
intermediate and earliest period (Table \ref{tab:input_n}).  
We assumed average values of 100 and 50 for the BTS and
ATS data, respectively with inter-annual variability reflecting the
variability in the number of hauls sampled for ages. The tuning aspects for
these effective sample size weights were estimated following Francis 2011
(equation TA1.8, hereafter referred to as Francis weights).

## Parameters estimated outside of the assessment model
### Natural mortality and maturity at age

The baseline 16.1 (and 16.2) model specification has been to use constant
natural mortality rates at age (M=0.9, 0.45, and 0.3 for ages 1, 2, and 3+
respectively (Wespestad and Terry 1984). 
When predation was explicitly considered estimates
tend to be higher and more variable (Holsman et al. _this volume_; Holsman et
al. 2015; Livingston and Methot 1998; Hollowed et al. 2000). 
Clark (1999) found that specifying a
conservative (lower) natural mortality rate may be advisable when natural
mortality rates are uncertain. More recent studies confirm this (e.g., Johnson 
et al. 2015). 

In the supplemental multi-species assessment model alternative values of age
and time-varying natural mortality are presented. As in past years the
estimates indicate higher values than used here.  In the 2018 assessment we
evaluated natural mortality it was noted that the survey age compositions favored lower
values of _M_ while the fishery age composition favored higher values.  This is
consistent with the patterns seen in the BTS survey data as they show
increased abundances of “fully selected” cohorts. Hence, given the model
specification (asymptotic selectivity for the BTS age composition data), lower
natural mortality rates would be consistent with those data. Given these
trade-offs, structural model assumptions were held to be the same as previous
years for consistency (i.e., the mortality schedule presented below).

Maturity-at-age values used for the EBS pollock assessment were originally
based on Smith (1981) and were reevaluated (e.g., Stahl 2004; Stahl and
Kruse 2008a; and Ianelli et al. 2005). These studies found inter-annual
variability but general consistency with the current assumed schedule of
proportion mature at age. 

The values assumed for pollock natural mortality-at-age and maturity-at-age (for all models; Smith 1981) 
were kept the same as in previous assessments:

\begin{table}[ht]
\centering
\label{tab:dataextent}
\scalebox{0.9}{
\begin{tabular}{rrrrrrrrrrrrrrrr}
\hline
Age&1&2&3&4&5&6&7&8&9&10&11&12&13&14&15 \\
\hline
$M$&0.90&0.45&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30 \\
$P_{mat}$&0.00&0.008&0.29&0.64&0.84&0.90&0.95&0.96&0.97&1.00&1.00&1.00&1.00&1.00&1.00 \\
\hline
\end{tabular}
}
\end{table}


### Length and weight-at-age
Age determination methods have been validated for pollock (Kimura et al. 1992;
Kimura et al. 2006, and Kastelle and Kimura 2006). EBS pollock size-at-age
show important differences in growth with differences by area, year, and
year class. Pollock in the northwest area are typically smaller at age than
pollock in the southeast area. The differences in average weight-at-age are
taken into account by stratifying estimates of catch-at-age by year, area,
season, and weighting estimates proportional to catch.

The assessment model for EBS pollock accounts for numbers of individuals in
the population. As noted above, management recommendations are based on
allowable catch levels expressed as tons of fish. While estimates of pollock
catch-at-age are based on large data sets, the data are only available up
until the most recent completed calendar year of fishing (e.g., 2019 for this
year). Consequently, estimates of weight-at-age in the
current year are required to map total catch biomass (typically equal to the
quota) to numbers of fish caught (in the current year). Therefore, if there
are errors (or poorly accounted uncertainty) in the current and future mean
weight-at-age, this can translate directly into errors between the expected
fishing mortality and what mortality occurs. For example, if the mean weight at
age is biased high, then an ABC (and OFL) value will result in greater numbers
of fish being caught (and fishing mortality being higher due to more fish
fitting within the ABC).

To explore patterns in size-at-age and fish condition, we applied the extensive
fishery observer data weight given length. We began by standardizing for length
over all available years and areas (1991--2020) as follows:
 
  1. extract all data where non-zero measurements of pollock length and weight 
	 were available between the lengths of 35 and 60 cm for the EBS region

  2. compute the mean value of body mass (weight) for each cm length bin 
      over all areas and time

  3. divide each weight measurement by that mean cm-specific value (the "standardization" step)

  4. plot these standardized values by different areas, years, months etc. to evaluate condition 
	 differences (pooling over ages is effective as there were no size-specific biases apparent)

In the first instance, the overarching seasonal pattern in body mass relative
to the mean shows that as the winter progresses prior to peak spawning,
pollock are generally skinnier than average whereas in July, the median is
about average (Fig. \ref{fig:fsh_lw_month}). As the summer/fall progresses,
fish were at their heaviest given length (Fig. \ref{fig:fsh_lw_month}). This
is also apparent when the data are aggregated by A- and B-seasons (and by east
and west of 170$^\circ$W; referred to as SE and NW respectively) when plotted
over time (Fig. \ref{fig:fsh_lw_anom_str_yr_box}). 
Combining across seasons, the fishery data show that the 2020 fish were well
below average weight given length (Fig. \ref{fig:fsh_lw_anom_yr_box}).

Examining the weight-at-age, there are also consistent patterns of variability
that vary due to environmental conditions in addition to spatial and temporal 
patterns of the fishery. Based on the bootstrap distributions and large sample
sizes, the within-year sampling variability for pollock is small.
However, the between-year variability in mean weights-at-age is relatively high
(Table \ref{tab:wtage}). The coefficients of variation between years are on the 
order of 6\% to 9\% (for the ages that are targeted) whereas the sampling variability 
is generally around 1\% or 2\%. The approach to account for the identified 
mean weight-at-age having clear year and cohort effects was continued (e.g., Fig. \ref{fig:fsh_wtage_comb}).
Details were provided in appendix 1A of Ianelli et al. (2016). The results
from this method showed the relative variability between years and cohorts and
provide estimates (and uncertainty) for `r paste0(thisyr,"--",thisyr+2)`
(Table \ref{tab:wtage}). How these fishery weights-at-age estimates can be supplemented
using survey weights-at-age is further illustrated in Fig. \ref{fig:fish_wtage_data_pred}.

In the 2020 fishery, the average weight-at-age was below average for the 
2012-2014 year classes. These cohorts have fluctuated around their means
in recent years (Fig. \ref{fig:fsh_wtage_comb}). To examine this more closely, 
we split the bootstrap results into area-season 
strata and were able to get an overall picture of the pattern by strata (Fig. \ref{fig:fsh_wtage_strata}) 
and Fig. \ref{fig:fsh_wtage_strata_yr}). This showed that the mean weight-at-age is
higher in the the B-season in the area east of 170$^\circ$W compared to the
A-season and B-season in the area west 170$^\circ$W.


## Parameters estimated within the assessment model

For the selected model, `r M$npar` parameters were estimated conditioned on data and
model assumptions. Initial age composition, subsequent recruitment, and stock-
recruitment parameters account for 79 parameters. This includes vectors
describing the initial age composition (and deviation from the equilibrium
expectation) in the first year (as ages 2--15 in 1964) and the recruitment mean
and deviations (at age 1) from 1964--`r lastyr` and projected recruitment variability
(using the variance of past recruitments) for five years (`r paste0(nextyr,"--",nextyr+5)`). The two-
parameter stock-recruitment curve is included in addition to a term that
allows the average recruitment before 1964 (that comprises the initial age
composition in that year) to have a mean value different from subsequent
years. Note that the stock-recruit relationship is fit only to stock and
recruitment estimates from 1978 year-class through to the `r thisyr-2` year-class.

Fishing mortality is parameterized to be semi-separable with year and age
(selectivity) components. The age component is allowed to vary over time;
changes are allowed in each year. The mean value of the age component is
constrained to equal one and the last 5 age groups (ages 11--15) are specified
to be equal. This latter specification feature is intended to reduce the
number of parameters while acknowledging that pollock in this age-range are
likely to exhibit similar life-history characteristics (i.e., unlikely to
change their relative availability to the fishery with age). The annual
components of fishing mortality result in `r n<-thisyr-1963 ` `r n` 
parameters and the age-time
selectivity schedule forms a 10x`r paste0(n," matrix of ",10*n) ` 
parameters bringing the total
fishing mortality parameters to `r n+n*10`. The rationale for including time-
varying selectivity has recently been supported as a means to improve
retrospective patterns (Szuwalski et al. 2017) and as best
practice (Martell and Stewart, 2013).

For surveys and indices, the treatment of the catchability coefficient, and
interactions with age-specific selectivity require consideration. For the BTS
index, selectivity-at-age is estimated with a logistic curve in which year
specific deviations in the parameters is allowed. Such time-varying survey
selectivity is estimated to account for changes in the availability of pollock
to the survey gear and is constrained by pre-specified variance terms. For the
AT survey, which originally began in 1979 (the current series including data
down to 0.5 m from bottom begins in 1994), optional parameters to allow for
age and time-varying patterns exist but for this assessment and other recent
assessments, ATS selectivity is constant over time. Overall, five
catchability coefficients were estimated: one each for the early fishery
catch-per-unit effort (CPUE) data (from Low and Ikeda, 1980), the early bottom
trawl survey data (where only 6 strata were surveyed), the main bottom trawl
survey data (including all strata surveyed), the AT survey data, and the AVO
data. An uninformative prior distribution is used for all of the indices. The
selectivity parameters for the 2 main indices total 135 (the CPUE and AVO data
mirror the fishery and AT survey selectivities, respectively).

Additional fishing mortality rates used for recommending harvest levels are
estimated conditionally on other outputs from the model. For example, the
values corresponding to the $F_{40\%}$ $F_{35\%}$ and $F_{MSY}$ harvest rates are found by
satisfying the constraint that, given age-specific population parameters
(e.g., selectivity, maturity, mortality, weight-at-age), unique values exist
that correspond to these fishing mortality rates. The likelihood components
that are used to fit the model can be categorized as:

  *	Total catch biomass (log-normal, $\sigma=0.05$)
  * Log-normal indices of pollock biomass; bottom trawl surveys assume annual
   estimates of sampling error, as represented in Fig. \ref{fig:bts_biom} along with the 
   covariance matrices (for the density-dependent and VAST index series); for the AT index
   the annual errors were specified to have a mean CV of 0.20; while for the AVO
   data, a value relative to the AT index was estimated and scaled to have a mean CV of 
   0.3).
  *	Fishery and survey proportions-at-age estimates (multinomial 
   	with effective sample sizes presented Table \ref{tab:input_n}).
  *	Age 1 index from the AT survey (CV set equal to 30\% as in prior assessments).    
  *	Selectivity constraints: penalties/priors on age-age variability, time changes, and decreasing (with age) patterns.
  *	Stock-recruitment: penalties/priors involved with fitting a stochastic 
    stock-recruitment relationship within the integrated model.
  *	“Fixed effects” terms accounting for cohort and year sources of variability
     in fishery mean weights-at-age estimated based on available data from 1991-`r lastyr` from the fishery (and 1982-`r thisyr` for the bottom-trawl survey
     data) and externally estimated variance terms as described in 
     Appendix 1A of Ianelli et al. (2016; see Fig. \ref{fig:fish_wtage_data_pred}).  

Work evaluating temperature and predation-dependent effects on the stock-
recruitment estimates continues (Spencer et al. 2016). This approach modified
the estimation of the stock-recruitment relationship by including the effect
of temperature and predation mortality. A relationship between recruitment
residuals and temperature was noted (similar to that found in Mueter et al.,
2011) and lower pollock recruitment during warmer conditions might be
expected. Similar results relating summer temperature conditions to subsequent
pollock recruitment for recent years were also found by Yasumiishi et al.
(2015). 

# Results
## Model evaluation

A sequential sensitivity of available new data showed that adding the 2020
fishery  catch-at-age data and the 2021 catch biomass information was
relatively uninformative  with respect to spawning biomass estimates (Fig. \ref{fig:mod_data}).  
As the new 2021 bottom-trawl survey estimates were added to the model (named Model 20.0), 
the biomass estimate dropped since the recent biomass estimate was lower than expected (Fig. \ref{fig:mod_data}). 
Addition of the 2021 length composition and preliminary catch-at-age data
had a minor impact on biomass and recruitment (Fig. \ref{fig:mod_21_agecomp}). 
Diagnostics of model fits between the set evaluated are given in Table \ref{tab:mod_fits} 
and comparisons of management quantities are given in Table \ref{tab:mgt_quants}).
For setting advice, we selected Model 20.0 with the additional 2021 fishery age composition 
data. While the data are preliminary, we considered that including them was worthwhile 
given the relative impact on selectivity. 

In the 2020 assessment, SRR evaluations related to Tier 1 classification showed that dropping the
influence of the 1978 year-class in the estimation lowered the steepness of the
curve and that when the influence of the prior
distribution was removed the residual pattern for estimates near the origin was particularly 
bad (all below the curve). From those results we conclude that the prior specification was
appropriate because we place priority on fitting estimated recruits near 
the slope at the origin better. Last year's assessment also showed that 
conditioning the SRR to fit the condition of having the "actual" $F_{MSY}$ equal some $F_{MSY}$ 
proxies (e.g., equal $F_{35\%}$) shows that the results 
were more conservative (shallower initial slopes). 
A conclusion from these exercises was that the SPR proxy for $F_{MSY}$ implies a 
reasonable "shape" to the SRR. 

The fit to the early Japanese fishery CPUE data (Low and Ikeda 1980) was
consistent with the estimated population trends for this period (Fig.
\ref{fig:mod_cpue_fit}).   The model fits the fishery-independent index from
the 2006--2021 AVO data well through most of the period but the model predicts lower biomass 
than the index data indicate (Fig. \ref{fig:mod_avo_fit}). 
The model fits to the bottom-trawl survey biomass (the
density-dependent corrected series) were good (Fig.
\ref{fig:mod_bts_biom}). Similarly, the fits to the  acoustic-trawl survey
biomass series (including the USV data from 2020) was consistent with the specified observation uncertainty (Fig.
\ref{fig:mod_ats_biom}).

The estimated parameters and standard errors are provided [online](https://apps-afsc.fisheries.noaa.gov/Plan_Team/2021/EBSPollock_params.pdf).
The code for the model (with dimensions and links to parameter names) and input files are available on request.

The input sample size (as tuned in 2016 using "Francis Weights") can be
evaluated visually for consistency with expectations of mean annual age for
the different gear types (Fig. \ref{fig:mod_mean_age}; Francis 2011). The
estimated selectivity pattern  changes over time and reflects to some degree
the extent to which the fishery is focused on particularly prominent year-
classes (Fig. \ref{fig:mod_fsh_sel}). The model fits the fishery age-
composition data quite well under this form of selectivity (Fig. \ref{fig:mod_fsh_age}). 

Bottom-trawl survey selectivity (Fig. \ref{fig:mod_bts_sel}) and fits to the
pollock biomass index indicate that the model predicts fewer
pollock than observed in the 2014 and 2015 survey but slightly more than
observed in the years since then (Fig. \ref{fig:mod_bts_biom}). The
pattern of bottom trawl survey age composition data in recent years shows a
decline in the abundance of older pollock since 2011. The 2006 year-class
observations are below model expectations in 2012 and 2013. This is partly due
to the fact that in 2010 the survey estimates are greater than the model predictions
(Fig. \ref{fig:mod_bts_age}). The model predicted much higher proportions of
age 6 (2012 year class) than observed in the 2018 survey data whereas the
expectations of 5-year old pollock were much lower than observations (both
surveys indicated that the 2013 year class was more abundant than the 2012
year-class).

The fit to the ATS biomass index survey generally falls within the confidence bounds of the survey sampling
distributions (here assumed to have an average CV of 20\%) with a reasonable
pattern of residuals (Fig. \ref{fig:mod_ats_biom}). The AT age compositions
consistently track large year classes through the population and the model
fits these patterns reasonably well (Fig. \ref{fig:mod_ats_age}).

As in past assessments, an evaluation of the multivariate posterior
distribution  was performed by running a chain of 3 million Monte-Carlo Markov
chain (MCMC) simulations and saving every 600th iteration (final posterior
draws totaled 5,000). We evaluated how selected parameters relate by doing a pairwise 
(along with their marginal distributions) figure (Fig. 
\ref{fig:mcmc_pairs}). This illustrates how key parameters relate to management parameters of interest.
For example, the stock recruitment steepness is negatively correlated to the resulting 
$B_{MSY} estimate. We also compare the point estimates (highest posterior density) with the mean of the 
posterior marginal distribution of the `r thisyr` spawning biomass. This showed that the point estimate was
similar to the mean of the marginal posterior distribution (Fig. \ref{fig:mcmc_marg}). 
As an additional part of the Tier 1 consideration, we evaluated the posterior
density of $F_{MSY}$. This indicates that the measure of uncertainty accounting 
(i.e., the probability density function or PDF) for $F_{MSY}$ seems reasonably approximated 
by this assessment model (Fig. \ref{fig:mcmc_marg_fmsy}). 


## Time series results
The time series of begin-year biomass estimates (ages 3 and older) suggests
that the abundance of Eastern Bering Sea pollock remained at a high level from
1982--88, with estimates ranging from 8 to 11 million t (Table \ref{tab:biom_3plus}). 
Historically, biomass levels increased from 1979 to
the mid-1980s due to the strong 1978 and relatively strong 1982 and 1984 year
classes recruiting to the fishable population. The stock is characterized by
peaks in the mid-1980s, the mid-1990s and again appears to be increasing to
new highs over 13 million t in 2016 following the low in 2008 of 
`r round(M$age3plus[45]/1000,2)` million t. The estimate for 
`r thisyr` is trending downward and at 
`r round(M$age3plus[length(M$age3plus)]/1000,2)` million t.
with `r nextyr` estimated at `r round(M$age3plus1/1000,2)` million t.

The level of fishing relative to biomass estimates show that the spawning
exploitation rate (SER, defined as the percent removal of egg production in
each spawning year) has been mostly below 20\% since 1980 (Fig. \ref{fig:mod_ser}).
During 2006 and 2007 the rate averaged more than 20\% and the average fishing
mortality for ages 3--8 increased during the period of stock decline. The
estimate for 2009 through 2019 was below 20\% due to the reductions in TACs
relative to the maximum permissible ABC values and increases in the spawning
biomass. The average F (ages 3--8) increased in 2011 to above 0.25 when the TAC
increased but has dropped since then and in `r thisyr` is estimated at about 17\%.
Age specific fishing mortality rates reflect these patterns and show some
increases in the oldest ages from 2011--2013 but also indicate a decline in
recent years (Fig. \ref{fig:mod_F}). The estimates of age 3+ pollock
biomass are generally similar over different years of assessments (Fig. \ref{fig:mod_hist},
Table \ref{tab:biom_3plus}).

Estimated numbers-at-age are presented in (Table \ref{tab:est_n}) and
estimated catch-at-age values are presented in (Table \ref{tab:est_catage}).
Estimated summary biomass (age 3+), female spawning biomass, and age-1
recruitment are given in  (Table \ref{tab:biom_ssb_rec}).

To evaluate past management and assessment performance it can be useful to
examine estimated fishing mortality relative to reference values. For EBS
pollock, we computed the reference fishing mortality from Tier 1 (unadjusted)
and recalculated the historical values for $F_{MSY}$ (since selectivity has
changed over time). Since 1977 the current estimates of fishing mortality
suggest that during the early period, harvest rates were above $F_{MSY}$ until
about 1980. Since that time, the levels of fishing mortality have averaged
about 35\% of the $F_{MSY}$  level (Fig. \ref{fig:mod_phase}). 
Projections of spawning stock biomass given the `r thisyr+1` estimate of
fishing mortality rate given catches equal to the `r thisyr` values shows a 
decline through 2021 and then an increase after; albeit with 
considerable uncertainty due to uncertainty in recruitment 
(Fig. \ref{fig:proj_ssb}). 

## Recruitment

Model estimates indicate that the 2008, 2012, and 2013 year classes are 
above average (Fig. \ref{fig:mod_rec}). The stock-recruitment curve as
fit within the integrated model shows a fair amount of variability both in the
estimated recruits and in the uncertainty of the curve (Fig. \ref{fig:mod_srr}). 
Note that the 2019 and 2020 year classes (as age 1 recruits in
2020 and 2021) were excluded from the stock-recruitment curve estimation.
Separate from fitting the stock- recruit relationship within the model,
examining the estimated recruits-per-spawning biomass shows variability over
time but seems to lack trend and also is consistent with the Ricker stock-
recruit relationship used within the model (Fig. \ref{fig:mod_rs}).


Environmental factors affecting recruitment are considered important and
contribute to the variability. Previous studies linked strong Bering Sea
pollock recruitment to years with warm sea temperatures and northward
transport of pollock eggs and larvae (Wespestad et al. 2000; Mueter et al.
2006). As part of the Bering-Aleutian Salmon International Survey (BASIS)
project research has also been directed toward the relative density and
quality (in terms of condition for survival) of young-of-year pollock. For
example, Moss et al. (2009) found age-0 pollock were very abundant and widely
distributed to the north and east on the Bering Sea shelf during 2004 and 2005
(warm sea temperature; high water column stratification) indicating high
northern transport of pollock eggs and larvae during those years. Mueter et
al. (2011) found that warmer conditions tended to result in lower pollock
recruitment in the EBS. This is consistent with the hypothesis that when sea
temperatures on the eastern Bering Sea shelf are warm and the water column is
highly stratified during summer, age-0 pollock appear to allocate more energy
to growth than to lipid storage (presumably due to a higher metabolic rate),
leading to low energy density prior to winter. This then may result in
increased over-winter mortality (Swartzman et al. 2005, Winter et al. 2005).
Ianelli et al. (2011) evaluated the consequences of current harvest policies
in the face of warmer conditions with the link to potentially lower pollock
recruitment and noted that the current management system is likely to face
higher chances of ABCs below the historical average catches.
Also, as part of the evaluation of stationarity given periods of "regimes", 
we revisited estimated mean recruitment during different periods previously 
identified as being unique. This show an pattern consistent with the impact of
warming on recruits with the period from 2000--present having below average
the current regime (since 1977) average (Fig. \ref{fig:mod_regimes}).


## Retrospective analysis
Running the assessment model over a grid with progressively fewer years
included (going back to 20 years, i.e., assuming the data extent ended in
`r thisyr-20`) results in a fair amount of variability in both spawning biomass and
recruitment (Fig. \ref{fig:mod_retro}). This year with the lower than expected survey biomass estimate,
the retrospective pattern degraded considerably with an increased 
average bias (Mohns $\rho$ equal to `r round(rhoMohn10,3)`
 for the 10 year retrospective and `r round(rhoMohn20,3)` if extended  back 20-years). 

In response to the SSC's request to evaluate how selectivity is used for ABC and catch advice, 
we used the retrospective runs to show how the "projected" selectivity compared with subsequent estimates
which had the benefit of more data. In 2020, the projected selectivity was towards younger fish but in 
general, the projected selectivity conformed reasonably well with subsequent estimates (Fig. \ref{fig:retro_sel}). 
We also computed a summary statistic of the mean age of selection (independent of any age-specific stock size) which
showed that recently the projection was biased towards younger pollock but earlier on, the bias was toward older fish 
(Fig. \ref{fig:retro_sel_mnage}).

Since selectivity varies over time, and the fact that fishing mortality rates for management advice depends
on the assumed future selectivity, we evaluate the pattern of $F_{MSY}$ rates given different selectivity assumptions 
(XXFig and elaboration to come...)



# Harvest recommendations
## Status summary

The estimate of $B_{MSY}$ is `r M$bmsys` kt (with a CV of 
  `r round(100*(M$bmsy.sd/M$bmsy),0)`\%)  which is `r if(M$bmsy<M$nextyrssb) {"less"}else{"more"}`
than the projected 
`r nextyr` spawning biomass of `r M$nextyrssbs` kt;  (Table
\ref{tab:res_summ}).  For `r thisyr`, the estimates put the stock in Tier 1`r if(M$bmsy<M$curssb) {"a"}else{"b"}`.
The corresponding maximum permissible ABC would thus be
`r M$maxabc1s` t with a fishable biomass estimated at around `r M$ABC_biom1s` kt
(Table \ref{tab:tier1_proj}). For the current year spawning biomass this corresponds to `r round(M$curssb/M$bmsy*100,0)`\%  of the
$B_{MSY}$ level). A diagnostic (see section below on model details) on the impact 
of fishing shows that the `r thisyr` spawning stock size is about 
`r round(100*M$dynb0,0)`\%  of the predicted value had no fishing occurred
 since 1978 (Table \ref{tab:res_summ}). 

Compared to Tier 3 projections, the results indicate that spawning biomass in
`r nextyr` will be about `r round(100*M$curssb/M$b100,0)`\% 
of $B_{100}$\% (based on the SPR expansion using mean recruitment from 1978--`r thisyr -2`). 
This would put the stock in Tier 3`r if(M$curssb>(M$b100*.4)) {"a and above"}else{"b and below"}`
$B_{40\%}$ and result in a `r paste(thisyr,"ABC of",M$Tier3_ABC1s,"t")`.

The probability that the current stock size is below 20\% of $B_{0}$ (a level important for additional
management measures related to Steller sea lion recovery) 
is <0.1\% for `r thisyr+1` and `r nextyr+1`.


In response to a request from the SSC, this year we added results from projections based on Tier 2.
We base the "standard" Tier 2 ABC calculation using the point estimate (the mean of the posterior 
distribution) of $F_{MSY}$.
Therefore, for `r nextyr` the Tier 2`r if(M$bmsy<M$curssb) {"a"}else{"b"}`
ABC would be `r M$Tier2_ABC1s ` t. 
Since we have estimates of the harmonic mean (from Tier 1 calculations) 
an alternative Tier 2 estimate using that in place of the arithmetic mean 
$F_{MSY}$ results in an ABC of `r M$Tier1.5_ABC1s ` t. 

In summary, the criterion for Tier 1 depends on a reliable estimate of 
$F_{MSY}$ and the uncertainty (the PDF). Tier 2 also requires a reliable estimate of 
$F_{MSY}$ (without the PDF requirement). Given the seemingly reasonable posterior marginal
density for $F_{MSY}$, it seems if Tier 1 criterion are unmet, then so would the requirement
for Tier 2. Adopting Tier 3, while in principle may result in more conservative catch advice, 
it uses less information available about the stock productivity and requires adopting more
assumptions.


## Amendment 56 Reference Points

Amendment 56 to the BSAI Groundfish Fishery Management Plan (FMP) defines
overfishing level (OFL), the fishing mortality rate used to set OFL (FOFL),
the maximum permissible ABC, and the fishing mortality rate used to set the
maximum permissible ABC. The fishing mortality rate used to set ABC
($F_{ABC}$) may be less than this maximum permissible level, but not greater.
Estimates of reference points related to maximum sustainable yield (MSY) are
currently available. However, their reliability is questionable. We therefore
present both reference points for pollock in the BSAI to retain the option for
classification in either Tier 1 or Tier 3 of Amendment 56. These Tiers require
reference point estimates for biomass level determinations. Consistent with
other groundfish stocks, the following values are based on recruitment
estimates from post-1976 spawning events:

\begin{table}[ht]
\begin{tabular}{lr}
$B_{MSY}$    &=	`r M$bmsys` kt female spawning biomass    \\
$B_{0}$      &=	`r M$b0s` kt female spawning biomass    \\
$B_{100\%}$  &=	`r M$b100s` kt female spawning biomass   \\
$B_{40\%}$   &=	`r M$b40s` kt female spawning biomass    \\
$B_{35\%}$   &=	`r M$b35s` kt female spawning biomass    \\
\end{tabular}
\end{table}

## Specification of OFL and Maximum Permissible ABC

Assuming the stock-recruit relationship the `r nextyr` spawning biomass is
estimated to be `r M$ssb1s` t (at the time of spawning, assuming the stock is
fished at about recent catch levels). 
This means that the stock is `r if(M$bmsy>M$nextyrssb) {"below"}else{"above"}`
the $B_{MSY}$ value of `r M$bmsys`,000 t.

This would put the stock in Tier 3`r if(M$curssb>(M$b100*.4)) {"a and above"}else{"b and below"}`
`r M$bmsys`,000 t. 
xxxUnder Amendment 56, this stock has qualified under Tier 1 and
the harmonic mean value is considered a risk-averse policy since reliable
estimates of $F_{MSY}$ and its pdf are available (Thompson 1996). The
exploitation- rate type value that corresponds to the $F_{MSY}$ level was
applied to the fishable biomass for computing ABC levels. For a future year,
the fishable biomass is defined as the sum over ages of predicted begin-year
numbers multiplied by age specific fishery selectivity (normalized to the
value at age 6) and mean body mass. The uncertainty in the average
weights-at-age projected for the fishery and “future selectivity” has been
demonstrated to affect the buffer between ABC and OFL (computed as 1-ABC/OFL)
for Tier 1 maximum permissible ABC (Ianelli et al. 2015). The uncertainty in
future mean weights-at-age had a relatively large impact as did the
selectivity estimation.

Since the `r nextyr` female spawning biomass is estimated to be above the $B_{MSY}$ level
(`r M$bmsys` kt) and the $B_{40\%}$ value (`r M$b40s` kt) in `r nextyr` and if the `r thisyr` catch
is as specified above, then the OFL and maximum permissible ABC values by the
different Tiers would be:

```{r abctab13}
df <- data.table(Tier=c("1a","1a","3a","3a"), Year=c(nextyr,nextyr+1,nextyr,nextyr+1),
	              MaxABC=c(M$maxabc1s,M$maxabc2s,formatC(c(M$Tier3_ABC1*1000,M$Tier3_ABC2*1000),digits=0,format="d",big.mark=",")),OFL=c(M$ofl1s,M$ofl2s,M$Tier3_OFL1s,M$Tier3_OFL2s))
tab <- xtable(df, digits = c(0,0,0,0,0),big.mark="," )
print(tab,include.rownames=F,big.mark=",",hline.after=c(-1,0,2,nrow(tab)))
```

## Standard Harvest Scenarios and Projection Methodology

A standard set of projections is required for each stock managed under Tiers
1, 2, or 3 of Amendment 56 to the FMP. This set of projections encompasses
seven harvest scenarios designed to satisfy the requirements of Amendment 56,
the National Environmental Policy Act, and the Magnuson-Stevens Fishery
Conservation and Management Act (MSFCMA). While EBS pollock is generally
considered to fall within Tier 1, the standard projection model requires
knowledge of future uncertainty in $F_{MSY}$ . Since this would require a
number of additional assumptions that presume future knowledge about
stock-recruit uncertainty, the projections in this subsection are based on
Tier 3.

For each scenario, the projections begin with the vector of `r thisyr` numbers
at age estimated in the assessment. This vector is then projected forward to
the beginning of `r nextyr` using the schedules of natural mortality and
selectivity described in the assessment and the best available estimate of
total (year- end) catch assumed for `r thisyr`. In each subsequent year, the
fishing mortality rate is prescribed on the basis of the spawning biomass in
that year and the respective harvest scenario. Annual recruits are simulated
from an inverse Gaussian distribution whose parameters consist of maximum
likelihood estimates determined from the estimated age-1 recruits. Spawning
biomass is computed in each year based on the time of peak spawning and the
maturity and weight schedules described in the assessment. Total catch is
assumed to equal the catch associated with the respective harvest scenario in
all years. This projection scheme is run 1,000 times to obtain distributions
of possible future stock sizes and catches under alternative fishing mortality
rate scenarios.

Five of the seven standard scenarios will be used in an Environmental
Assessment prepared in conjunction with the final SAFE. These five scenarios,
which are designed to provide a range of harvest alternatives that are likely
to bracket the final TAC for `r nextyr`, are as follows (“$maxFABC$” refers to
the maximum permissible value of FABC under Amendment 56):

\begin{description}
\item[Scenario 1:]   
In all future years, $F$ is set equal to max$F_{ABC}$. (Rationale:  Historically,
TAC has been constrained by ABC, so this scenario provides a likely upper
limit on future TACs).

\item[Scenario 2:]   
In `r nextyr` and `r nextyr+1` the catch is set equal to 1.35 million t
and in future years $F$ is set equal to the Tier 3 estimate (Rationale: this 
has been about equal to the catch level in recent years).

\item[Scenario 3:]   
In all future years, $F$ is set equal to the `r thisyr-6;print("-");thisyr-1` average $F$. (Rationale:
For some stocks, TAC can be well below ABC, and recent average $F$ may provide a
better indicator of $F_{TAC}$ than $F_{ABC}$.)

\item[Scenario 4:]   
Scenario 4: In all future years, $F$ is set equal to $F_{60\%}$. (Rationale:  This
scenario provides a likely lower bound on $F_{ABC}$ that still allows future
harvest rates to be adjusted downward when stocks fall below reference levels.

\item[Scenario 5:]   
Scenario 5: In all future years, $F$ is set equal to zero. (Rationale:  In
extreme cases, TAC may be set at a level close to zero.)

\item[Scenario 6:]   
In all future years, F is set equal to $F_{OFL}$. (Rationale:  This scenario
determines whether a stock is overfished. If the stock is expected to be 
1) below its MSY level in `r thisyr` or 2) below half of its MSY level in `r thisyr` or below
its MSY level in `r thisyr +10` under this scenario, then the stock is overfished.)

\item[Scenario 7:]   
In `r nextyr` and `r nextyr+1`, F is set equal to $maxFABC$, and in all subsequent years, F
is set equal to $F_{OFL}$. (Rationale:  This scenario determines whether a stock is
approaching an overfished condition. If the stock is 1) below its MSY level in
`r nextyr+1` or 2) below 1/2 of its MSY level in `r nextyr+1` and expected to be below its MSY
level in `r thisyr+12` under this scenario, then the stock is approaching an
overfished condition).

\end{description}

The latter two scenarios are needed to satisfy the MSFCMA’s requirement to
determine whether a stock is currently in an overfished condition or is
approaching an overfished condition (for Tier 3 stocks, the MSY level is
defined as $B_{35\%}$).

## Projections and status determination

For the purposes of these projections, we present results based on selecting
the $F_{40\%}$ harvest rate as the $F_{ABC}$ value and use $F_{35\%}$ as a
proxy for $F_{MSY}$. Scenarios 1 through 7 were projected 14 years from 
`r thisyr` (Tables 35 through \ref{tab:tier3_SSB} for Model 16.1 and for 16.2--the 
configuration that uses the NBS VAST data set). Under the
catch set to Tier 3 ABC estimates, the expected spawning biomass will
decline until 2020 and stabilize slightly above $B_{40\%}$ (in expectation,
Fig. \ref{fig:tier3_proj}).

Any stock that is below its minimum stock size threshold (MSST) is defined to
be overfished. Any stock that is expected to fall below its MSST in the next
two years is defined to be approaching an overfished condition. Harvest
scenarios 6 and 7 are used in these determinations as follows:

Is the stock overfished? This depends on the stock’s estimated spawning
biomass in `r thisyr`:

* If spawning biomass for `r thisyr ` is estimated to be below 1/2 $B_{35\%}$ the stock is below its MSST.   

* If spawning biomass for `r thisyr ` is estimated to be above $B_{35\%}$, the stock is above its MSST.   

* If spawning biomass for `r thisyr` is estimated to be above 1/2 $B_{35\%}$ but below $B_{35\%}$,
 the stock’s status relative to MSST is determined by referring to harvest
 scenario 6 ((Tables \ref{tab:tier3_C} through \ref{tab:tier3_SSB}). If the mean spawning biomass for
 `r thisyr + 10` is below $B_{35\%}$, the stock is below its MSST. Otherwise, the stock is
 above its MSST.

Is the stock approaching an overfished condition?  This is determined by
referring to harvest Scenario 7:

* If the mean spawning biomass for 2018 is below 1/2 $B_{35\%}$, the stock is approaching an overfished condition.  

* If the mean spawning biomass for 2018 is above $B_{35\%}$, the stock is not approaching an overfished condition.  

* If the mean spawning biomass for `r nextyr+1` is above 1/2 $B_{35\%}$ but below $B_{35\%}$, the
  determination depends on the mean spawning biomass for 2028. If the mean
  spawning biomass for `r nextyr+11` is below $B_{35\%}$, the stock is approaching an
  overfished condition. Otherwise, the stock is not approaching an overfished
  condition.

For scenarios 6 and 7, we conclude that pollock is above MSST for the year 
`r thisyr`,  and it is expected to be above the "overfished condition" based on
Scenario 7 (the mean spawning biomass in `r thisyr` is above the $B_{35\%}$
estimate; (Table \ref{tab:tier3_SSB}). Based on this, the EBS pollock stock is
being fished below the overfishing level and the stock size is estimated to be
above, and stay above the overfished level.

To fulfill reporting requirements for the Species Information System, each 
model was used to reverse-engineer the fishing mortality rate corresponding to the 
specified OFL for the last complete year (`r thisyr-1`). This reverse-engineered $F_{OFL}$ 
values ($RE F_{OFL}$) is 0.508.


## ABC Recommendation

ABC levels are affected by estimates of $F_{MSY}$ which
depends principally on the estimated stock-recruitment steepness parameter,
demographic schedules such as selectivity-at-age, maturity, and growth. The
current stock size (both spawning and fishable) is estimated to be  below
average levels and projections indicate the potential for further declines.  Updated data and
analysis result in an estimate of `r thisyr` spawning biomass (`r M$curssbs`
kt) which is about  `r round(100*M$curssb/M$bmsy,0)`\% of $B_{MSY}$ 
(`r M$bmsys` kt).  This follows a period of increases from
2008--2017. The extent that the stock will decline further depends  on recruitment, which 
given the available information, is uncertain.
Given the same estimated aggregate fishing effort in 2021, the 
estimated stock trend is downwards except at low catch levels. Furthermore, 
the ability to catch roughly the same amount as in `r thisyr` 
through to 2023 will require more effort (effectively) and will result
in further declines in spawning biomass.

### Should the ABC be reduced below the maximum permissible ABC?

The SSC in its September 2018 minutes recommended that assessment authors and
Plan Teams use the risk matrix table below when determining whether to
recommend an ABC lower than the maximum permissible. 

\pagebreak

\begin{table}[ht]
\scalebox{0.88}{
\begin{tabular}{C{0.7in}L{1.5in}L{1.5in}L{1.5in}L{1.5in}}
\hline
 &\multicolumn{4}{c}{\textbf{Considerations}} \\
\hline
 &\textbf{Assessment-related} & \textbf{ Population dynamics} & \textbf
 {Environmental \& ecosystem }    & Fishery performance \\
\hline
Level 1 Normal   
& Typical to moderately increased uncertainty \& minor unresolved issues in assessment       
& Stock trends are typical for the stock; recent recruitment is within normal range.    
& No apparent environmental \& ecosystem concerns  
&  No apparent fishery/resource-use performance and/or behavior concerns \\ 
Level 2 Substantially increased concerns & Substantially increased assessment uncertainty unresolved issues.
& Stock trends are unusual; abundance increasing or decreasing faster than has been seen
  recently, or recruitment pattern is atypical. 
& Some indicators showing an adverse signals but the pattern is inconsistent
across all indicators. 
& Some indicators showing adverse signals but the pattern is inconsistent
across all indicators. \\
Level 3 Major Concern                    
& Major problems with the stock assessment, very poor fits to data, high level of 
uncertainty, strong retrospective bias. 
& Stock trends are highly unusual; very rapid changes in stock abundance, or highly atypical recruitment patterns.                           
& Multiple indicators showing consistent adverse signals a) across the same trophic level, 
and/or b) up or down trophic levels (i.e., predators and prey of stock) 
& Multiple indicators showing consistent adverse signals a) across different sectors, 
and/or b) different gear types

\\
Level 4 Extreme concern                  
& Severe problems with the stock assessment, severe retrospective bias. Assessment considered unreliable.          
& Stock trends are unprecedented. More rapid changes in stock abundance than have ever been seen previously, or a very long stretch of poor recruitment compared to previous patterns. 
& Extreme anomalies in multiple ecosystem indicators that are highly likely to impact the stock. Potential for cascading effects on other ecosystem components    
& Extreme anomalies in multiple performance indicators that are highly like to
impact the stock.
\\
\hline
\end{tabular}
}
\end{table}

The table is applied by evaluating the severity of four types of
considerations that could be used to support a scientific recommendation to
reduce the ABC from the maximum permissible. Examples of the types of concerns that
might be relevant include the following (as identified by the work-group):  

  1. Assessment considerations  
    -  _Data-inputs:_ biased ages, skipped surveys, lack of fishery-independent trend data  
    -  _Model fits:_ poor fits to fits to fishery or survey data, inability to simultaneously fit multiple data inputs.  
    -  _Model performance:_ poor model convergence, multiple minima in the likelihood surface, parameters hitting bounds.  
    -  _Estimation uncertainty:_ poorly-estimated but influential year classes.  
    -  Retrospective bias in biomass estimates.  

  2. Population dynamics considerations—decreasing biomass trend, poor recent
  recruitment, inability of the stock to rebuild, abrupt increase or decrease
  in stock abundance.  
  
  3. Environmental/ecosystem considerations--trends in
  environmental/ecosystem indicators, ecosystem model results, decreases in
  ecosystem productivity, decreases in prey abundance or availability,
  increases or increases in predator abundance or productivity. 

  4. Fisheries considerations--fishery CPUE is showing a contrasting pattern 
    from the stock biomass trend, unusual spatial pattern of fishing, changes in
   the percent of TAC taken, changes in the duration of fishery openings.” 

*Assessment considerations*   The EBS pollock assessment model has appeared
to track the  stock from year based on retrospective analysis in previous 
assessment. This year however, the lower than expected survey observation
lowered the recent biomass estimates and the retrospective analysis indicated
a tendency to over estimate the stock trend.
 The model tracks the available data reasonably well except for the strong 
 increase in the AVO index relative to 2019.
The abundance estimate from the NBS was down 
and relative to population age composition, the pattern in the 2012 and 2013 year-classes
is unusual.
 **We therefore rated the assessment-related concern as level 2, substantially increased concern.**

*Population dynamics considerations*  The age structure of EBS pollock  has
exhibited some peculiarities over time. On the positive side, some strong
year-classes appear to have increased in abundance based on the bottom-trawl
survey data (e.g., the 1992, 2012 and 2013 year classes). Conversely, the period
from 2000--2007 had relatively poor year-class strengths which resulted in
declines in stock below $\it{B_{msy}}$ and reduced TACs due to lower ABC
values. Presently it appears that the mean recruitment since 2000 has been 
below average (Fig. \ref{fig:mod_regimes}). 
There also are clear density-dependent effects on growth, in
particular, the 2012 year class. The stock is estimated to be  below
$\it{B_{msy}}$ at present, and projections indicate a reasonable chance that the stock will
decline further given recent catch levels.
The extent that the the lack of a cold pool and
will impact pollock survival at egg, larval,
and juvenile stages is uncertain.
Recruitment in the near term could be below average yet projections
assume average recruitment (with uncertainty).
Additional age-specific aspects of the spawning population indicates that the
stock has increased from  a low diversity of ages (for both the
population and the mean age of the spawning stock weighted by spawning output
Fig. \ref{fig:age_diversity}). 
We also recognize that the stock-recruitment relationship selected for this cannibalistic
species requires a relatively informative prior distribution in order to 
have the residuals of the estimates relative to the curve to be less biased nearer
the slope of the origin. This could be interpreted as being undesirable and having undue 
influence on the underlying stock productivity (noting that it has been demonstrated
that the prior leads to increased conservativism).

**We therefore rated the population-dynamics concern as level 2, substantially increased concern.**

 *Environmental/Ecosystem considerations*\footnote{Provided by: Elizabeth Siddon, NOAA/AFSC} 

*Environmental processes* 
Beginning in approximately 2014, the eastern Bering Sea (EBS) entered a warm phase of unprecedented
duration. The EBS remains in this warm phase, though to a lesser degree compared to the extreme
years of 2018 and 2019. Sea ice formation in fall of 2020 was delayed due to residual warmth in the
system. While the areal extent of sea ice was closer to the pre-2014 levels than at any point in the
last 7 years, ice thickness differed between the northern (thicker ice) and southern (thinner/no
ice) shelves due to opposing prevailing winds (see Physical Environment Synthesis in Siddon, 2021).
The summer 2021 cold pool remained significantly reduced in area, and its southern boundary was
shifted northwestward. The areal extent of the cold pool has increased since 2018, yet the 2021
extent was the 4th lowest on record and remains more than one standard deviation below the mean
(Rohan and Barnett, 2021a). Summer bottom temperatures varied spatially over the shelf. Near-average
conditions were present over the SEBS, while the NBS had a very warm inner domain (i.e., Norton
Sound) and a small cold pool over the middle domain to the southwest of St. Lawrence Island (Rohan
and Barnett, 2021b).

Multiple ecosystem ‘red flags’ occurred in the NBS this year: crab population declines (Richar,
2021), salmon run failures in the Arctic-Yukon-Kuskokwim region (Liller, 2021), and seabird die-offs
combined with low colony attendance and poor reproductive success (see Integrated Seabird
Information in Siddon, 2021). In addition, results from the bottom trawl survey demonstrate a
substantial drop in total CPUE in the NBS between 2019 and 2021 that reflected large decreases in
all of the dominant species, including pollock (Mueter and Britt, 2021). Whether a single or suite
of mechanisms can be identified to explain these coincident events, the common thread in these
collapses is the marine environment in the NBS. Concerns about the food web dynamics and carrying
capacity in the NBS have existed since 2018, highlighted by the gray whale Unusual Mortality Event
and short-tailed shearwater mass mortality event (Siddon and Zador, 2019).

Fish condition, as measured by length-weight residuals, trended downward from 2019 for multiple
groundfish species, including benthic, pelagic, and apex predators, across both the southern and
northern portions of the survey area (Rohan and Prohaska, 2021), indicating poor feeding conditions
across trophic niches. While adult pollock (>25 cm) followed this trend of decreasing condition
based on length/weight residuals in the southern and northern survey areas, juvenile pollock
(100-250 mm) showed positive residuals in both regions (Rohan and Prohaska, 2021), indicating
sufficient foraging conditions existed for juvenile pollock. The information on pollock condition
based on fishery standardized mean weights-given-length was also relatively low during 2020 and 2021 
(Fig. \ref{fig:fsh_lw_anom_yr_box}).

Age-0 fish experiencing warm temperatures during late summer followed by relatively cooler
temperatures in spring of age-1 are thought to have below average survival. Based on this
Temperature Change index, the 2020 year class is predicted to have below-average recruitment to
age-4 in 2024 (Yasumiishi, 2021).


*Prey* 
The spring bloom over the south inner and middle domains occurred at or slightly later than the
long-term average. In comparison, at mooring M2, 2017 was among the earliest spring blooms while
2018 was among the latest (Nielsen et al., 2021). Chlorophyll concentrations in these regions have
been below the long-term median since 2016, although the south inner region was at the median value
in 2021 (Nielsen et al., 2021). Depending on the spatial and temporal overlap of productivity, this
can result in a match or mismatch with favorable feeding conditions for larval pollock.

Small copepods form the prey base for larval to early juvenile pollock during spring. Late juvenile
pollock feed on a variety of planktonic crustaceans, including calanoid copepods and euphausiids.
Pollock diets become more piscivorous with age and cannibalism is commonly observed. In 2021, over
the southern shelf, the springtime abundance of small copepods was within historical ranges and
large copepods appeared on-track to be available for age-0 fish later in the year (Kimmel et al.,
2021). In addition, higher abundances of adult euphausiids were observed which, if persistent
through summer, would also provide a significant food source to forage fish (Kimmel et al., 2021).
Over the northern shelf in late summer, similar zooplankton patterns were observed with low
abundances of small copepods, but slight increases in the abundance of large copepods and
euphausiids (Kimmel et al., 2021). The annual ration of EBS pollock (Holsman et al., 2021)?

*Predators* 
Pollock are cannibalistic and rates of cannibalism might be expected to increase as the biomass of
older, larger fish increases. In 2020, with an average cold pool extent over the shelf, predation
pressure from cannibalism may have been mitigated by this thermal barrier as adult pollock tend to
avoid the cold bottom waters. In 2021, a small retracted cold pool likely offered no thermal refuge
or barrier for juvenile pollock. However, the biomass of pelagic foragers, including adult pollock
dropped in 2021 to their second lowest value over the time series (Whitehouse, 2021a). With the
exception of Pacific herring, the 2021 index for all other species and functional groups in the
pelagic forager guild were below their long term means (Whitehouse, 2021a).

Fur seal consumption of adult pollock generally increases in years when juvenile pollock are less
abundant (Kuhn et al., 2019). However, no information on population trends for fur seals is
available since 2019.

Other potential predators of juvenile pollock include jellyfish and chum salmon. Jellyfish abundance
was high in 2019 (among the top 4 highest years since 1982), but declined to low abundance in 2021
(Britt, 2021). Chum salmon abundance has been declining precipitously in the Arctic-Yukon-Kuskokwim
Region since 2017 to their lowest level in the time series in 2021 (Liller, 2021), a trend also
reflected in the commercial harvest data (Whitehouse, 2021b).

*Competitors* 
The 2021 Bristol Bay sockeye salmon inshore run was the largest on record since 1963 (Cunningham et
al., 2021). Juvenile sockeye salmon feed on zooplankton (competitors with age-0 pollock) and age-0
pollock (competitors with adult pollock) in warm years; adults feed on zooplankton and krill. The
widespread die-off event of short-tailed shearwaters in 2019 slowed in 2020 (Siddon, 2020), with an
uptick in die-off numbers in 2021 especially in the northern Bering Sea (see Integrated Seabird
Information in Siddon, 2021). Shearwaters are planktivorous birds and feed on euphausiids in the
Bering Sea in summer. The die-off event of 2019 is thought to reflect poor foraging conditions for
birds during summer 2018 as most sampled birds showed signs of emaciation; the event of 2021 may
reflect strains on the carrying capacity of the northern Bering Sea region.



**Summary for Environmental/Ecosystem considerations:**  

  - The eastern Bering Sea has been in a prolonged warm phase since 2014;

  - Extent of sea ice was closer to pre-2014 levels than at any point in the last 7 years,

  - Sea ice thickness differed between the northern (thicker ice) and southern (thinner/no ice)
    shelves due to opposing prevailing winds;

  - The cold pool was reduced in area and its southern boundary was shifted northwestward;

  - Concerns about the food web dynamics and carrying capacity in the NBS have existed since 2018
    and may reflect poor feeding conditions in the northern Bering Sea;

  - Condition of adult pollock (as measured by length/weight residuals) trended down across the
    Bering Sea while juvenile pollock showed positive condition, indicating sufficient foraging
    conditions existed for juvenile pollock;

  - The 2020 year class experienced unfavorable temperature conditions from age-0 to age-1 and is
    predicted to have below-average recruitment to age-4 in 2024;

  - Spring bloom timing and chlorophyll concentrations over the southern shelf were average in 2021.

  - Zooplankton composition in spring indicated potentially favorable foraging conditions for age-0
    pollock through summer, especially over the southern shelf.

  - Predation pressure from cannibalism may have been mitigated by declines in biomass of pelagic
    foragers, including adult pollock.

  - Predation pressure from jellyfish and chum salmon was also reduced due to relative declines in
    the abundance of jellyfish and chum salmon over the shelf.

  - Bristol Bay sockeye salmon compete with both juvenile and adult pollock for prey (zooplankton,
    euphausiids, age-0 pollock), therefore sustained high inshore runs of sockeye salmon may have
    system-wide impacts on foraging success of pollock.

**We therefore rated the Ecosystem concern as Level 2, substantially increased concern.**


*Fishery performance* As noted above, the 2021 B-season fishery was
improved over 2020 but there remains concern about small pollock in the catches.
Also, an approach to computing fleet dispersion (the relative
distance or spread of the fishery in space)  was developed and indicated that
while the seasonal dispersion levels was below average indicating that the fishery 
was less spread out than normal (Fig \ref{fig:fleet_dispersal}).

The CPUE of PSC species and other bycatch moderated some relative to 2020.
Sablefish, herring and Chinook salmon bycatch rates (per hour of fishing) decreased
from 2020 but chum salmon had a marked increase (Fig. \ref{fig:fsh_psc_cpue}).

The mean weight-at-age for the 2020 B-season was near average, but in general pollock were skinny given their
length, and the fact that in 2020 a significant component of the catch was 2-year old pollock 
which are rarely found in the catch led us to **conclude that  the fishery 
performance scored a value of 2, substantially increased concerns.**

These results are summarized as:
\begin{table}[h]
\begin{tabular}{L{1.125in}L{1.125in}L{1.125in}L{1.125in}L{1.125in} }
\hline
 \multicolumn{4}{c}{Considerations}  & \\
Assessment-related & Population dynamics  & Environmental or ecosystem &Fisheries\\
\hline
Level 2: Substantially increased concerns & Level 2: Substantially increased concerns  &
Level 2: Substantially increased concerns & Level 2: Substantially increased concerns  \\
\hline
\end{tabular}
\end{table}

Having all four scores at level 2 suggests that setting an ABC below the
maximum permissible is warranted. 
The SSC recommended against using a table that showed example alternatives to select
buffers based on that risk level. Thompson (unpublished Sept 2018 plan team
document) tabulated the magnitude of buffers applied by the Plan Teams for the
period 2003--2017, and found that the mode of the buffers recommended was
10--20\%. Using this as a guideline, a buffer of 15\% would give an ABC as
$0.85 \times \text{ABC}_{max}$ = 
`r formatC(M$maxabc1*0.850,big.mark=",",digits=0,format="d")` 
kt). In the past,
the SSC has considered factors similar to those presented above  and selected
an ABC based on Tier 3 estimates. We recommend this added precaution 
again this year, (i.e., 
ABC = `r formatC(as.numeric(M$Tier3_ABC1),big.mark=",",digits=0,format="d")` kt) 
which implies a
buffer of  `r round(100*(1-M$Tier3_ABC1/M$maxabc1),0)`\%.   The SSC requested
"an explicit set of concerns that explain the ABC adjustment." In response, we
direct attention to the decision table \ref{tab:dec_table}) and the fact that the biological basis 
for the continued stock productivity has most to do with the OY constraint
which has  effectively maintained fishery production at around 1.3 million t
since 1990. Demonstrations that would allow fishing to near $F_{MSY}$ catch
quantities would show that catch  variability would be extremely high (and
unrealistic give current capacity and OY limits for combined BSAI groundfish;
Ianelli 2005). Furthermore, the frequency of being at much lower spawning
stock sizes would be much higher, and would likely be riskier and fishing
effort would need to be much higher. While the biological basis for ABC
setting is founded in  sound conservation of spawning biomass, the history of
the current fishery productivity should inform desirable biomass. In only 5
of the 38 years since 1981 has the stock been below the $B_{MSY}$ level (13%
of the years). The mean spawning biomass over this period has  averaged about
30% higher than the estimated $B_{MSY}$. In terms of an actual "management
target", Punt et al. (2013) developed some robust estimators for $B_{MEY}$
(Maximum Economic Yield) noting that a typical target would be 1.2$\times
B_{MSY}$. In this case that would make the female spawning biomass target at
`r round(1.2*M$bmsy/1000,3) ` million t. It therefore  seems worth considering
making an explicit harvest control rule that achieves the  productivity and
ecosystem stability given the catches and biomass estimates 
observed over  the past 30 years. 

In recent years when the pollock biomass was estimated to be well above average,
the catch was constrained by other factors. Specifically, the 2
million t BSAI groundfish catch limit and bycatch avoidance measures has an
impact on the potential for large increases in catch. As the stock is presently
estimated to be below $B_{MSY}$, the maximum permissible ABC under the FMP 
can become the limiting factor for TAC specification. Unfortunately, this ABC
can ratchet down quickly because as the stock declines further
below this target stock size, the ABC fishing mortality rate t is adjusted 
downwards nearly proportionately. This part of the FMP control rule can create
high variability in the TAC. Less variability in the catch, accordingly, 
 would also result in less spawning stock variability and reduce risks to the
fishery should the period of poor recruitment continue.  
To more fully evaluate these considerations performance indicators as modified from Ianelli
et al. (2012) were developed to evaluate some near-term risks given 
alternative `r nextyr` catch values.  These indicators and rationale for
including them are summarized in Table \ref{tab:dec_tab_rationale}).   Model
16.1 results for these indicators are provided in  Table \ref{tab:dec_table}.
Each column of this table uses a fixed `r nextyr` catch and assumes the same
effort  for the four additional projection years (`r nextyr+1`--`r nextyr+4`).
 Given this specification , there is a low probability that any of the catches
  shown in the first row would exceed the $F_{MSY}$ level.  Also, in the near
term it appears unlikely that the spawning stock will be below $B_{MSY}$ (rows
3 and 4).  Relative to the historical mean spawning biomass, by `r nextyr` it
is more likely than not that the spawning biomass will be lower than the
historical mean (fifth row). The range of catches examined have relatively
small or no impact on  the age diversity indicators. However, for catch to
equal the 2021 value, more fishing effort will likely be required
and there is a good chance that the proportion of the stock less than age 6 will be
greater than the historical average. In terms of catch advice, the results presented in 
the decision table indicates that catches above 1.0 million t will very likely result in 
`r nextyr+1` spawning stock estimates being below the long term mean (but above $B_{MSY}$).

Another approach/rationale would be to stabilize effort from the 2021 levels and
recommend that 2022 fishing mortality is set equal to the 2021 estimate. This
gives an ABC of `r M$abc1constFs ` kt. The Plan Teams and SSC may wish to
consider this as an added measure of precaution for ABC considerations.
  
# Additional ecosystem considerations

In general, a number of key issues for ecosystem conservation and management can be highlighted. These include:    

  * Preventing overfishing;    

  * Avoiding habitat degradation;    

  * Minimizing incidental bycatch;    

  * Monitoring bycatch and the level of discards; and    

  * Considering multi-species trophic interactions relative to harvest policies.    

For the case of pollock in the Eastern Bering Sea, the NPFMC and NMFS continue
to manage the fishery on the basis of these issues in addition to the single-
species harvest approach (Hollowed et al. 2011). The prevention of overfishing
is clearly set out as the main guideline for management. Habitat degradation
has been minimized in the pollock fishery by converting the industry to
pelagic-gear only. Bycatch in the pollock fleet is closely monitored by the
NMFS observer program and managed on that basis. Discard rates of many species
have been reduced in this fishery and efforts to minimize bycatch continue.

In comparisons of the Western Bering Sea (WBS) with the Eastern Bering Sea
using mass-balance food-web models based on 1980--85 summer diet data, Aydin et
al. (2002) found that the production in these two systems is quite different.
On a per-unit-area measure, the western Bering Sea has higher productivity
than the EBS. Also, the pathways of this productivity are different with much
of the energy flowing through epifaunal species (e.g., sea urchins and
brittlestars) in the WBS whereas for the EBS, crab and flatfish species play a
similar role. In both regions, the keystone species in 1980--85 were pollock
and Pacific cod. This study showed that the food web estimated for the EBS
ecosystem appears to be relatively mature due to the large number of
interconnections among species. In a more recent study based on 1990--93 diet
data (see Appendix 1 of the Ecosystem Considerations chapter for methods),
pollock remain in a central role in the ecosystem. The diet of pollock is
similar between adults and juveniles with the exception that adults become
more piscivorous (with consumption of pollock by adult pollock representing
their third largest prey item).

Regarding specific small-scale ecosystems of the EBS, Ciannelli et al. (2004a,
2004b) presented an application of an ecosystem model scaled to data available
around the Pribilof Islands region. They applied bioenergetics and foraging
theory to characterize the spatial extent of this ecosystem. They compared
energy balance, from a food web model relevant to the foraging range of
northern fur seals and found that a range of 100 nautical mile radius encloses
the area of highest energy balance representing about 50% of the observed
foraging range for lactating fur seals. This has led to a hypothesis that fur
seals depend on areas outside the energetic balance region. This study
develops a method for evaluating the shape and extent of a key ecosystem in
the EBS (i.e., the Pribilof Islands). Furthermore, the overlap of the pollock
fishery and northern fur seal foraging habitat (see Sterling and Ream 2004,
Zeppelin and Ream 2006). 

A brief summary of these two perspectives (ecosystem effects on pollock stock
and pollock fishery effects on ecosystem) is given in (Table \ref{tab:pscbycatch}). Unlike the
food-web models discussed above, examining predators and prey in isolation may
overly simplify relationships. This table serves to highlight the main
connections and the status of our understanding or lack thereof.   

## Ecosystem effects on the EBS pollock stock

The pollock stock condition appears to have benefited substantially from the
recent conditions in the EBS. The conditions on the shelf during 2008
apparently affected age-0 northern rock sole due to cold
conditions and apparently unfavorable currents that retain them into the over-
summer nursery areas (Cooper et al. 2014). It may be that such conditions
favor pollock recruitment. Hollowed et al. (2012) provided an extensive review
of habitat and density for age-0 and age-1 pollock based on survey
data. They noted that during cold years, age-0 pollock were distributed
primarily in the outer domain in waters greater than 1$^\circ$C and during warm
years, age-0 pollock were distributed mostly in the middle domain. This
temperature relationship, along with interactions with available food in
early-life stages, appears to have important implications for pollock
recruitment success (Coyle et al. 2011). 

A separate section presented again this year updates a multispecies model with
more recent data and is presented as a supplement to the BSAI SAFE report. In
this approach, a number of simplifications for the individual species data and
fisheries processes (e.g., constant fishery selectivity and the use of
design-based survey indices for biomass). However, that model mimics the
biomass levels and trends with the single species reasonably well. It also
allows specific questions to be addressed regarding pollock TACs. For example,
since predation (and cannibalism) is explicitly modeled, the impact of
relative stock sizes on subsequent recruitment to the fishery can be now be
directly estimated and evaluated (in the model presented here, cannibalism is
explicitly accounted for in the assumed Ricker stock-recruit relationship).


## EBS pollock fishery effects on the ecosystem.

Since the pollock fishery is primarily pelagic in nature, the bycatch of non-
target species is small relative to the magnitude of the fishery  (Table
\ref{tab:nontargbycatch}). Jellyfish represent the largest component of the
bycatch of non-target species and had averaged around 5--6 kt per year but
more than doubled in 2014 but has dropped in 2015. The 2018 value was relatively 
high again. The data on non-target species shows a high degree of inter-annual
variability, which reflects the spatial variability of the fishery and high
observation error. This variability may reduce the ability to detect
significant trends for bycatch species.

The catch of other target species in the pollock fishery (defined as any trawl
 set where the catch represents more than 80\% of the catch) represents less
than 1% of the total pollock catch. Incidental catch of Pacific cod has varied
but in the past three years it is about half of the 2011 and 2012 levels
(Table \ref{tab:fmpbycatch}).  There has been a marked in increase in the
incidental catch of Pacific ocean perch, sablefish, and Atka mackerel and a
decrease in flatfish species. Proportionately, the incidental catch decreased
since the overall levels of pollock catch have increased since 2008. In fact,
the bycatch of pollock in other target fisheries is more than double the
bycatch of target species in the pollock fishery (Table
\ref{tab:pollbycatch}).

The number of non-Chinook salmon (nearly all made up of chum salmon) taken
incidentally has steadily increased since 2014 with 2017 number in excess of
465 thousand fish but the 2018 level was slightly more than the
2003--2017 average of 227 thousand fish; Table \ref{tab:pscbycatch}). Chinook
salmon bycatch has also increased steadily since 2012 with the 2017 counts at
just below 30,000 (which was 18% below the 2003--2017 mean value). In 2018-2020
the bycatch  dropped back down to 13.5 thousand fish  (Table
\ref{tab:pscbycatch}).  Ianelli and Stram (2014) provided estimates of the
bycatch impact on Chinook salmon runs to the coastal west Alaska region and
found that the peak bycatch levels exceeded 7% of the total run return. Since
2011, the impact has been estimated to be below 2%. Updated estimates  given
new genetic information and these levels of PSC as provided to the
Council continues to suggest that the impact is low.


# Data gaps and research priorities

The available data for EBS pollock are extensive yet many processes behind the
observed patterns continue to be poorly understood.  
The recent patterns of abundance observed in the northern Bering Sea provide an example.
As such, we recommend the following research priorities:

  -  Continue to investigate using spatial processes for estimation purposes (e.g.,
combining acoustic and bottom trawl survey data). The application of the
geostatistical methods (presented for comparative purposes in this assessment)
seems like a reasonable approach to statistically model disparate data sources
for generating better abundance indices. Also, examine the potential to use
pelagic samples from the BASIS survey to inform recruitment and subsequent
spatial patterns.

  - Develop methods to use spatio-temporal models to estimate composition information (i.e., length and age).

  -  Study the relationship between climate and recruitment and trophic
interactions of pollock within the ecosystem. This would be useful for improving
ways to evaluate the current and alternative fishery management system. In
particular, studies investigating the processes affecting recruitment of
pollock in the different regions of the EBS (including potential for influx
from the GOA) should be pursued.

 - Apply new technologies (e.g., bottom-moored echosounders) to evaluate pollock
 movement between regions and supplement this work with analytical approaches.

 - Expand genetic sample collections for pollock (and process available samples) and apply high resolution genetic tools for stock structure analyses.

# Acknowledgments

We thank the scientifically trained observers and the staff of the Fisheries and Monitoring Division at 
AFSC for their hard work. The diligence of survey staff who contribute immensely in collecting samples, especially
given these times is exceptional.  The AFSC age-and-growth department is
thanked for their continued excellence in promptly processing the samples used
in this assessment.  Finally, thanks to the many colleagues who provided edits
and suggestions to improve this document.

