library(PBSadmb,quietly=TRUE)
library(plotrix,quietly=TRUE)
library(ggplot2,quietly=TRUE)
library(RColorBrewer,quietly=TRUE)
library(doBy,quietly=TRUE)
library(tidyr,quietly=TRUE)
library(data.table,quietly=TRUE)
library(dplyr,quietly=TRUE)
library(Cairo,quietly=TRUE)
library(gridExtra,quietly=TRUE)
source("../R/AgeFitsSrv.R")
source("../R/plot-ssb.R")
source("../R/plot-ssb-rel.R")
source("../R/plot-srr.R")
source("../R/plot-bts.R")
source("../R/plot-likel.R")
source("../R/plot-eit.R")
source("../R/plot-mnage.R")
source("../R/plot-sel.R")
source("../R/AgeFits.R")
source("../R/plot-retro.R")
source("../R/plot-recruitment.R")
source("../R/af.r")

.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=18)) + theme(axis.title.x=element_text(size=24) ,axis.title.y=element_text(size=24))
.THEME <- .THEME + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),panel.grid.minor.y = element_line(colour="grey60", linetype="dashed"), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme( panel.background = element_rect(fill="white"), panel.border = element_rect(colour="black", fill=NA, size=1))
.OVERLAY <- TRUE