#library(PBSadmb,quietly=TRUE)
#library(plotrix,quietly=TRUE)
#library(ggplot2,quietly=TRUE)
#library(RColorBrewer,quietly=TRUE)
#library(doBy,quietly=TRUE)
#library(dplyr,quietly=TRUE)
#library(tibble,quietly=TRUE)
#library(reshape2,quietly=TRUE)
#library(Cairo,quietly=TRUE)
#library(gridExtra)
#library(tidyverse,quietly=TRUE)
library(tidyverse,quietly=TRUE)
library(data.table,quietly=TRUE)
library(xtable)
options(xtable.comment = FALSE)
library(flextable)
library(ggplot2,quietly=TRUE)
library(ggthemes,quietly=TRUE)
library(grid,quietly=TRUE)
library(gridExtra,quietly=TRUE)
library(ggridges,quietly=TRUE)
#install.packages("ggridges")
cwd <- getwd()
#setwd("~/OneDrive/ebswp/EBSpollock/runs")
#setwd("~/_mymods/_ebswp/runs")
source("../R/print_Tier3_tables.R")
source("../R/tab-fit.R")
source("../R/get-vars.R")
source("../R/read-admb.R")
source("../R/plot-agefit.R")
source("../R/plot-ssb.R")
source("../R/plot-ssb-rel.R")
source("../R/plot-R-rel.R")
source("../R/plot-srr.R")
source("../R/plot-bts.R")
source("../R/plot-cpue.R")
source("../R/plot-likel.R")
source("../R/plot-ats.R")
source("../R/plot-avo.R")
source("../R/plot-mnage.R")
source("../R/plot-sel.R")
source("../R/plot-ser.R")
source("../R/plot-recruitment.R")
#source("../R/AgeFits.R")
#source("../R/plot-retro.R")
source("../R/af.r")
setwd(cwd)
#
.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=12)) + theme(axis.title.x=element_text(size=14) ,axis.title.y=element_text(size=14))
#.THEME <- .THEME + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),panel.grid.minor.y = element_line(colour="grey60", linetype="dashed"), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme( panel.background = element_rect(fill="white"), panel.border = element_rect(colour="black", fill=NA, size=1))
.OVERLAY <- TRUE
